### ISSUE TITLE
Boost bootstrap failure

### ISSUE THREAD

**Issue by alastair-radcliffe** [bempp/bempp#170]
Hi,

I'm trying to build bempp on my Suse-linux-11 machine with cmake version 2.8.11.2 using 

export OMP_NUM_THREADS=1
CC=gcc-4.7 CXX=g++-4.7 cmake /where/i/put/bempp
make

which works on another machine running the same linux, cmake etc, but for some reason gives me the following on my home machine:

...
[  2%] Performing configure step for 'Boost'
CMake Error at /home/masnaj/mod/bempp-build/external/src/Boost-stamp/Boost-configure.cmake:17 (message):
  Command failed: 1
   './bootstrap.sh'
  See also
    /home/masnaj/mod/bempp-build/external/src/Boost-stamp/Boost-configure-*.log
make[2]: *** [external/src/Boost-stamp/Boost-configure] Error 1
make[1]: *** [CMakeFiles/Boost.dir/all] Error 2
make: *** [all] Error 2

The bootstrap.log contains:

$:~/mod/bempp-build> more bootstrap.log
###
###
rm -rf bootstrap
mkdir bootstrap
gcc -o bootstrap/jam0 command.c compile.c constants.c debug.c execcmd.c frames.c function.c glob.c hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c make.
c make1.c object.c option.c output.c parse.c pathsys.c regexp.c rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c class.
c cwd.c native.c md5.c w32_getreg.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modules/order.c execunix.c fileunix.c pathu
nix.c
./bootstrap/jam0 -f build.jam --toolset=gcc --toolset-root= clean
...found 1 target...
...updating 1 target...
...updated 1 target...
./bootstrap/jam0 -f build.jam --toolset=gcc --toolset-root=
...found 158 targets...
...updating 3 targets...
[MKDIR] bin.linuxx86_64
[COMPILE] bin.linuxx86_64/b2
[COPY] bin.linuxx86_64/bjam
cp: preserving permissions for `bin.linuxx86_64/bjam': Operation not supported

        cp -Rpf "bin.linuxx86_64/b2" "bin.linuxx86_64/bjam"
    
...failed [COPY] bin.linuxx86_64/bjam...
...removing bin.linuxx86_64/bjam
...failed updating 1 target...
...updated 2 targets...

Any ideas ? ... do i simply need more permissions on my local machine ?

Thanks,

Alastair

**Comment by wroberts** [comment]
I'm going to guess that `cp: preserving permissions for bin.linuxx86_64/bjam: Operation not supported` is the key here.  Could you be trying to build on a network share, by any chance?
