### ISSUE TITLE
python3 bempp master branch - import error

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#179]
Hello,

importing bempp in a python3 environment fails because of a missing ``libdunegrid.so`` file. This file does not get installed to ``$PREFIX/lib64`` when calling ``make install``. A temporary fix is to add ``$builddir/external/lib64`` to the ``LD_LIBRARY_PATH``.

Furthermore, importing bempp.lib fails as well due to a missing lib.py file in site-packages/bempp.

Regards
Thomas

**Comment by getzze** [comment]
I had the same problem and solved it by modifying `cmake_install.cmake` in the `build` subfolder.
Duplicate lines 35 to 37 and replace `lib` by `lib64` in the two occurences. This is equivalent to adding the following line after line 37:

    if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
      file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib64" TYPE DIRECTORY FILES "/home/blacoste088/Documents/INL/gitprojects/bempp/build/external/lib64/")
    endif()
