### ISSUE TITLE
Interaction matrix in radiation problem

### ISSUE THREAD

**Issue by rbijster** [bempp/bempp#184]
hi,

I am currently trying to implement a BEM based method for radiative heat exchange (http://dx.doi.org/10.1103/PhysRevB.88.054305). Although the method relies on elements of the BEM, not the entire integral equations are solved. Rather, I am looking for the interactions between matrix elements. As I am not very much familiar with BEM, I am hoping you can help me getting started. 

Part of the solution is hidden in the equation:
![matrixequation8](https://cloud.githubusercontent.com/assets/10126860/5354404/9fda8400-7f87-11e4-8cd1-e2917001283a.png)
with matrix elements G_{m,n}^{r,ij} = < B_m^i, Gamma_r x B_n^i > , with <..> denoting the standard inner product <phi, psi> = int phi* psi and B_m and B_n the basis functions and the x indicating a convolution. I understand that this inner product is part of the Galerkin discretization. The four quadrants of the Gamma matrix are defined as
![matrixequationa1](https://cloud.githubusercontent.com/assets/10126860/5354456/7e394916-7f88-11e4-9bbc-cd6b92697c90.png) Unfortunately, the notation is inconsistent between papers. The elements of G and C in these expressions are given by
![matrixequationa4](https://cloud.githubusercontent.com/assets/10126860/5354709/f40b7170-7f8b-11e4-801e-5e86f3007c70.png)
In these equations G_0 is not related to the first equation above and is rather the Green's function for the Helmholtz equation
![matrixequationa5](https://cloud.githubusercontent.com/assets/10126860/5354461/95cc3b9c-7f88-11e4-9d1f-42dbd2d17330.png)

Part of this problem I recognized in the implemented operators for the Maxwell 3D problem, that also use the same kernel G_0. I understand that the mentioned inner products follow from the Galerkin discretization, but I have difficulties seeing how I can obtain these via BEM++. 

Your help is much appreciated.

Regards,

Roy

**Comment by rbijster** [comment]
Thanks for the help! The program seems to work. Still some minor bugs I have to hunt down, but nothing that seems related to the above :-).

Regards,
Roy

**Comment by rbijster** [comment]
Hi,

Unfortunately, I experience some weird scaling behaviour that I cannot trace. Just to rule out any scaling induced by the method discussed above, I would like to address to following point. 

You said that the lowest order Raviart-Thomas basis functions are equivalent the the RWG basis functions, as I also read elsewhere. However, I also read that the RWG functions are scaled with the length of the edge they correspond to (http://arxiv.org/pdf/1206.2161.pdf). Is there any scaling implemented in BEMpp? As we are only taking the integral of the basis functions, any scaling in the basis functions might have an influence here.

In the image below you see my results compared to those of the paper cited in my first post. As you can see, the code reproduces the same trend, but has a growing error with growing distance. 
![eerstevergelijking](https://cloud.githubusercontent.com/assets/10126860/5722334/85a3fd08-9b3b-11e4-98a6-7e97f3b3b75b.png)

Regards,

Roy

**Comment by wsmigaj** [comment]
Dear Roy,

the Raviart-Thomas basis functions in BEM++ are not "scaled with the edge length". The range of values of a Raviart-Thomas basis function on an element does not change if the element is scaled by a common factor in all three dimensions. You are right to point out that this differs from the behaviour of RWG basis functions (but both families span the same vector space).

I would be surprised, though, if this difference in scaling was responsible for the disagreement between the two curves on your plot, because the formulas in the paper are clearly derived for general basis functions (indeed, in one of the examples they are chosen as the tangential components of the vector spherical harmonics).

Best regards,
Wojciech

**Comment by rbijster** [comment]
Hi Wojciech,

You are right. In the trace expressions in the paper, the matrices G_i and W are multiplied. As W is the inverse of the sum of G_i, any scaling is cancelled there anyway.

In case you have any ideas that could cause this discrepancy that are related to BEM or the implementation discussed above, please shoot! :)

Best regards,

Roy

**Comment by rbijster** [comment]
Hi,

We managed to eliminate one bug in the implementation. The construction of one the matrices was incorrect in my code. This removed some of the errors. 

However, I have a question about the way the matrix forms of the weak form operators is formed.
Say I have object 1 with 150 edges and object 2 with 300 edges. In case I calculate the self-interaction matrix of object 1 (G1, G011) I expect 150 x 150 matrix subblocks G_EE, G_EH, G_HE and G_HH giving me a total of 300 x 300 elements in G1. For the second object this would be 600 x 600 for matrix G2.

If I then calculate the interaction matrix from object 1 to 2 (G012), I'd expect a 300x600 matrix and a 600x300 matrix vice versa (G021).

However, I noticed that the outputs for G012 and G021 is actually transposed. Is this the expected behaviour? Because they are transposed I cannot assemble the matrix G0hat which is composed of the blocks G011, G012, G021 and G022. 
It is simply solved by taking the transpose of G_EE, G_EH, G_HE and G_HH in calculating the blocks, but I'd like to know if this is okay. 

```python
## Calculate 'transfer' between two identities
def computeTransfer(context, source, target, Z, k, label=""):

	## Create operators. 
	# Arguments:(context, domain, range, dualToRange, wave number, label)
	slpOp = createMaxwell3dSingleLayerBoundaryOperator(
		context, source, target, target, k, label + ": SLP")
	dlpOp = createMaxwell3dDoubleLayerBoundaryOperator(
		context, source, target, target, k, label + ": DLP")
		
	# G convoluted with basis functions    
	G_ = slpOp.weakForm().asMatrix() * (1.0j / k)
	# C convoluted with basis functions
	C_ = dlpOp.weakForm().asMatrix() * (-1.0 / k)

	# Components of Gamma matrix convoluted with the basis vectors
	G_EE = 1.0j*k*Z*G_
	G_EH = 1.0j*k*C_
	G_HE = 1.0j*k*-1.0*C_
	G_HH = 1.0/Z*1.0j*k*G_
	
	# Compute G	
	G_EE = np.asmatrix(G_EE)
	G_EH = np.asmatrix(G_EH)
	G_HE = np.asmatrix(G_HE)
	G_HH = np.asmatrix(G_HH)

	Gret = np.bmat([[G_EE, G_EH], [G_HE, G_HH]])
	
	return Gret	

### SNIPPET:
	probeSpace = createRaviartThomas0VectorSpace(context, probeGrid) 
	substSpace = createRaviartThomas0VectorSpace(context, substGrid) 

	## Calculate the sub-blocks of the interaction matrices
	# Self-interactions of probe (1)
	G1 = computeTransfer(context, probeSpace, probeSpace, Z1, k1, label="G1")

	# Interactions between probe and substrate through the medium (0)
	G011 = computeTransfer(context, probeSpace, probeSpace, Z0, k0, label="G011")
	G012 = computeTransfer(context, probeSpace, substSpace, Z0, k0, label="G012")
	G021 = computeTransfer(context, substSpace, probeSpace, Z0, k0, label="G021")
	G022 = computeTransfer(context, substSpace, substSpace, Z0, k0, label="G022")

 G0hat = np.bmat([[G011, G012], [G021, G022]])
```

Regards,

Roy

**Comment by wsmigaj** [comment]
Dear Roy,

I'm glad you managed to find some mistakes in the code -- I regret I wasn't able to help you in that.

Regarding your current question: the code
```
slpOp = createMaxwell3dSingleLayerBoundaryOperator(
        context, source, target, target, k, label + ": SLP")
```
creates an operator whose domain space is ``source`` and the space dual to range is ``target``. Therefore the number of rows in its matrix will be equal to the number of global degrees of freedom in ``target``, and the number of columns will be equal to the number of global degrees of freedom in ``source``. Hence the symbols ``G012`` and ``G021`` in 
```
G012 = computeTransfer(context, probeSpace, substSpace, Z0, k0, label="G012")
G021 = computeTransfer(context, substSpace, probeSpace, Z0, k0, label="G021")
```
should be swapped.

Best regards,
Wojciech
