### ISSUE TITLE
Question about consultancy

### ISSUE THREAD

**Issue by RSamsonjvlk** [bempp/bempp#191]
Dear BEMPP-community,

Can anyone help me with the following? Does anybody know about an institution or a private person who has excellent BEMPP-skills and who would be willing (and able) to do some consultancy work on this subject? Grateful your reaction, RSamsonjvlk.

**Comment by tbetcke** [comment]
Hi,

This depends on the kind of consultancy. To discuss details please send me
a mail directly to t.betcke@ucl.ac.uk

Best wishes

Timo

On Friday, 2 January 2015, RSamsonjvlk <notifications@github.com> wrote:

> Dear BEMPP-community,
>
> Can anyone help me with the following? Does anybody know about an
> institution or a private person who has excellent BEMPP-skills and who
> would be willing (and able) to do some consultancy work on this subject?
> Grateful your reaction, RSamsonjvlk.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/191>.
>


-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519
