### ISSUE TITLE
[master] pkg_install/PyTrilinos does not exist

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#194]
I tried to compile the master branch of bempp with ``python setup.py build && python setup.py install``. Installation fails due to a missing PyTrilinos directory:

```
....
-- RPath patching /home/thomas/gitrepos/bempp/pkg_install/bempp/file_interfaces/__init__.so
-- RPath patching /home/thomas/gitrepos/bempp/pkg_install/bempp/file_interfaces/gmsh.so
running build_py
error: package directory 'pkg_install/PyTrilinos' does not exist
```

**Comment by tbetcke** [comment]
Thanks for spotting this. Mayeul, could you have a look when you have time?
PyTrilinos is not needed any more. So any dependencies on it can be removed.

Timo

On 4 January 2015 at 18:13, Thomas Hisch <notifications@github.com> wrote:

> I tried to compile the master branch of bempp with python setup.py build
> && python setup.py install. Installation fails due to a missing
> PyTrilinos directory:
>
> ....
> -- RPath patching /home/thomas/gitrepos/bempp/pkg_install/bempp/file_interfaces/__init__.so
> -- RPath patching /home/thomas/gitrepos/bempp/pkg_install/bempp/file_interfaces/gmsh.so
> running build_py
> error: package directory 'pkg_install/PyTrilinos' does not exist
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/194>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by mdavezac** [comment]
Mind that that tests do not all run yet (d4c3440) as per comments in #195
