### ISSUE TITLE
Fenics integration

### ISSUE THREAD

**Issue by tbetcke** [bempp/bempp#196]
We want to make it easier to create FEM/BEM solves with Fenics and BEM++. Some Fenics people have already created a first interfaces (see the [Magnum.fe](http://t.co/6uno0hdmVa)) project and we need this now for an internal project as well.

@mdavezac, could you check if the [Fenics binary release](http://fenicsproject.org/download/) could be made  to work together with the BEM++ master branch? We need to be able to import both, Fenics and BEM++ into the same Python session and can then do everything from the Python level.

**Comment by thisch** [comment]
I'm looking forward to it!

**Comment by mdavezac** [comment]
It does not look trivial, a priori. There are two concerns:

- the python used to compile Fenics and BEM++ must be the same:  if you are using a non-system python (eg homebrew, macport, or enthought) then Fenics will have to be compiled for that python (as will bem)
- there is at least on library in common, namely trilinos. If Fenics install Trilinos correctly, then we should be able to use it when compiling BEM. If not (missing includes, missing libs, missing  cmake files, non-standard install location) it could be really painful. 

For the record, this is a priori, not a result from actual testing.

**Comment by tbetcke** [comment]
I did ask on the Fenics mailing list. They sent me the list of dependencies that are minimally needed. The main part of their response was:

---------------
FIAT requires SymPy. DOLFIN requires

CMake >= 2.8
C++11 (C++0x) capable compiler
Boost >= 1.48
Eigen3
LibXML2

Optional packages are

OpenMP
MPI
PETSc
PETSc4py
SLEPc
SLEPc4py
Trilinos
UMFPACK
CHOLMOD
PaStiX
SCOTCH
ParMETIS
zlib
Python + SWIG >= 2.0 + NumPy
Sphinx
HDF5
VTK
QT

Minimally you would probably need LU solver, which is provided by
PETSc or UMFPACK.

-------------
Trilinos is only used for some graph partitioners. For now we don't need an MPI enabled Fenics. So a minimal installation should be fine, that is: The Fenics packages Fiat, Instant, FFC, UFL and Dolfin and the dependencies:

CMake >= 2.8
C++11 (C++0x) capable compiler
Boost >= 1.48
Eigen3
LibXML2

and in addition

UMFPACK for sparse linear solves, Swig for the Python interface and probably vtk for data export.

This should give us enough to test Fenics/BEM++ integration for now. 

The [dorsal.sh](http://fenicsproject.org/download/installation_using_dorsal.html) setup script from Fenics contains the library versions and download links of all Fenics packages.

Do you have resources to work on this at the moment?

**Comment by tbetcke** [comment]
Hi, I don't think that dorsal allows to pick and choose. Last time I used Dorsal (admittedly more than a year ago) it was quite a mess. However, it's scripts are helpful to see what library versions should be downloaded and what good compilation options are.

If you can integrate the dependencies into the BEM++ build system together with a fenics flag that enables optional compilation of Fenics I could easily take it from there and also tweak the build setup if necessary.

Timo

**Comment by mdavezac** [comment]
I'll give it a try. This could be quite hairy, so I'm not sure how much time it will take.
