### ISSUE TITLE
Greens repr theorem - potential operators that evaluate curl u

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#197]
Hi, 

I want to evaluate the curl of u in the exterior domain (u is a solution of Maxwell's equations). Am I right that I just have to use a different SLPOP and DLPOP, where the Greensfunction in these operators is replaced by the 'curl' of it (This follows from applying the curl operator to Green's repr theorem)? I guess that I have to write a custom operator for this or has someone already done this?

**Comment by wsmigaj** [comment]
Hi Thomas,

as shown by Buffa and Hiptmair on page 16 of [their paper on BEM for Maxwell equations](http://www.sam.math.ethz.ch/~hiptmair/Courses/CEM/BUH03.pdf), the curl of the single-layer potential operator is equal to the double-layer potential operator times the wavenumber, and the curl of the double-layer potential operator is equal to the single-layer potential operator times the wavenumber. (In BEM++ [we add an extra factor i](http://www.bempp.org/cppref/2.0/group__maxwell__3d.html) to the definition of the single-layer potential operator, so these relations will be slightly modified.)

Best regards,
Wojciech

**Comment by thisch** [comment]
Thx again Wojciech for your fast answer! So it looks like I don't have to write a custom operator - thats great.

Best regards
Thomas
