### ISSUE TITLE
complex conjugate of gridfunction

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#198]
Hi,

I would like to compute the complex conj. of an existing gridfunction (I don't want to modify the function which is passed to ``createGridFunction`` as the original gridfunction is needed in my code as well). I've tried 

```
tmp = dirichlet_data.coefficients()
tmp[:] = tmp.conj()
```
but this does not work as the coefficients() method returns a copy of the data and not a numpy view.

Regards
Thomas

**Comment by wsmigaj** [comment]
Hi Thomas,

see issue #94.

Best regards,
Wojciech
