### ISSUE TITLE
linking issues

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#199]
``ldd  $PREFIX/lib/python3.4/site-packages/bempp/assembly/boundary_operator.so`` lists a few libraries  for which it can't determine the path of the library on disk: (Therefore, importing bempp.assembly fails)

```
ldd  $PREFIX/`lib/python3.4/site-packages/bempp/assembly/boundary_operator.so G  'not found'
	libdunegrid.so => not found
	libdunegeometry.so => not found
	libdunecommon.so => not found
	libdunecommon.so => not found
	libdunegeometry.so => not found
	libdunegrid.so => not found
```

This seems to be a cmake issue as the ``boundary_operator.so`` file in the build directory (build/python_package) has the correct RPATHs set. 

```
for x in `find $BEMPPSRCDIR | grep /boundary_operator.so`; do echo $x; ldd $x | grep 'not found';  done
./pkg_install/bempp/assembly/boundary_operator.so
	libdunegrid.so => not found
	libdunegeometry.so => not found
	libdunecommon.so => not found
	libdunecommon.so => not found
	libdunegeometry.so => not found
	libdunegrid.so => not found
./build/lib.linux-x86_64-3.4/bempp/assembly/boundary_operator.so
	libdunegrid.so => not found
	libdunegeometry.so => not found
	libdunecommon.so => not found
	libdunecommon.so => not found
	libdunegeometry.so => not found
	libdunegrid.so => not found
./build/python_package/bempp/assembly/boundary_operator.so
```

```
~gr/bempp » ldd ./build/external/src/dune-grid-build/lib/libdunegrid.so
	linux-vdso.so.1 =>  (0x00007fffa7723000)
	libdunegeometry.so => /home/thomas/gitrepos/bempp/build/external/src/dune-geometry-build/lib/libdunegeometry.so (0x00007ff929314000)
	libdunecommon.so => /home/thomas/gitrepos/bempp/build/external/src/dune-common-build/lib/libdunecommon.so (0x00007ff9290ff000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff928db7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff928aaf000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff928897000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff9284da000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff9297d0000)

~gr/bempp » ldd ./build/external/lib64/libdunegrid.so                                                                                                                                                     
	linux-vdso.so.1 =>  (0x00007fff87154000)
	libdunegeometry.so => not found
	libdunecommon.so => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f2c6edba000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f2c6eab2000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2c6e89a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2c6e4dd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2c6f36f000)
```

**Comment by tbetcke** [comment]
In the build directory there is a script localpython.sh to run a Python
session with all correct paths automatically set. I have no problems with
this in OS X, Ubuntu and Fedora. How do you start the Python session?

Timo

On Sunday, 11 January 2015, Thomas Hisch <notifications@github.com> wrote:

> ldd $PREFIX/lib/python3.4/site-packages/bempp/assembly/boundary_operator.so
> lists a few libraries for which it can't determine the path of the library
> on disk: (Therefore, importing bempp.assembly fails)
>
> ldd  $PREFIX/`lib/python3.4/site-packages/bempp/assembly/boundary_operator.so G  'not found'
>     libdunegrid.so => not found
>     libdunegeometry.so => not found
>     libdunecommon.so => not found
>     libdunecommon.so => not found
>     libdunegeometry.so => not found
>     libdunegrid.so => not found
>
> This seems to be a cmake issue as the boundary_operator.so file in the
> build directory has the correct RPATHs set.
>
> for x in `find $BEMPPSRCDIR | grep /boundary_operator.so`; do echo $x; ldd $x | grep 'not found';  done
> ./pkg_install/bempp/assembly/boundary_operator.so
>     libdunegrid.so => not found
>     libdunegeometry.so => not found
>     libdunecommon.so => not found
>     libdunecommon.so => not found
>     libdunegeometry.so => not found
>     libdunegrid.so => not found
> ./build/lib.linux-x86_64-3.4/bempp/assembly/boundary_operator.so
>     libdunegrid.so => not found
>     libdunegeometry.so => not found
>     libdunecommon.so => not found
>     libdunecommon.so => not found
>     libdunegeometry.so => not found
>     libdunegrid.so => not found
> ./build/python_package/bempp/assembly/boundary_operator.so
>
> ~gr/bempp » ldd ./build/external/src/dune-grid-build/lib/libdunegrid.so
>     linux-vdso.so.1 =>  (0x00007fffa7723000)
>     libdunegeometry.so => /home/thomas/gitrepos/bempp/build/external/src/dune-geometry-build/lib/libdunegeometry.so (0x00007ff929314000)
>     libdunecommon.so => /home/thomas/gitrepos/bempp/build/external/src/dune-common-build/lib/libdunecommon.so (0x00007ff9290ff000)
>     libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff928db7000)
>     libm.so.6 => /lib64/libm.so.6 (0x00007ff928aaf000)
>     libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff928897000)
>     libc.so.6 => /lib64/libc.so.6 (0x00007ff9284da000)
>     /lib64/ld-linux-x86-64.so.2 (0x00007ff9297d0000)
>
> ~gr/bempp » ldd ./build/external/lib64/libdunegrid.so
>     linux-vdso.so.1 =>  (0x00007fff87154000)
>     libdunegeometry.so => not found
>     libdunecommon.so => not found
>     libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f2c6edba000)
>     libm.so.6 => /lib64/libm.so.6 (0x00007f2c6eab2000)
>     libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2c6e89a000)
>     libc.so.6 => /lib64/libc.so.6 (0x00007f2c6e4dd000)
>     /lib64/ld-linux-x86-64.so.2 (0x00007f2c6f36f000)
> ``
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/199>.
>


-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by thisch** [comment]
I start it from a conda environment (on Fedora)

**Comment by tbetcke** [comment]
I also use Anaconda with Fedora 21 on my workstation. In the build
directory you can start an IPython environment with ./localpython.sh -m
IPython. This has all shared library paths correctly set. Did you try this?

Timo

On Sunday, 11 January 2015, Thomas Hisch <notifications@github.com> wrote:

> I start it from a conda environment (on Fedora)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/199#issuecomment-69501818>.
>


-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by thisch** [comment]
yes, I don't see the error with the localpython.sh script.

I had a similar issue with the mshr project (see issue https://bitbucket.org/benjamik/mshr/issue/17/import-order-problem). However, here I don't see the ``-- Removed runtime path from xxxxx.so`` line in the cmake output.

**Comment by tbetcke** [comment]
Thanks. We had several problems with setting the runtime paths correctly on Mac and Linux. The localpython.sh script fixes this quite nicely so far. It will be renamed to something nicer for the release. If you don't mind I will close this for now.

**Comment by mdavezac** [comment]
This should be corrected by the cmake build system. I'll take a look as soon as I can. localpython.sh should really only be for debugging. We would want calling python to work...

**Comment by thisch** [comment]
I also think that this localpython.sh script should not be required  for a production build.

**Comment by thisch** [comment]
Since localpython.sh, 'bempp' or 'ibempp' don't get installed with a ``make install``, I've tried to determine the pythonpath and ld_library_path needed to successfuly import the bempp python module.  As long as I set the pythonpath to ``$BUILD_DIR/python_package`` importing bempp works, otherwise I get the importerror from above (https://github.com/bempp/bempp/issues/199#issuecomment-69501818).  

What's the difference between ``$BUILD_DIR/python`` and ``$BUILD_DIR/python_package``, as the files from ``$BUILD_DIR/python`` get installed to my anaconda ``$PREFIX`` and not the ones from ``$BUILD_DIR/python_package``?
