### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by samschnorr** [bempp/bempp#200]
Hey there,

I wanted to install BEM++ on my new system with Linux Mint 64bit Rebecca, but i got the following error:

python bempp_setup.py -b bempp_setup.cfg
Downloading dependencies
============================================================================== 
BEM++ INSTALLATION FAILED WITH ERROR MESSAGE: 
SSLFactory instance has no attribute 'get_https_connection'

You can read the bempp_setup.cfg file here:
http://pastebin.com/VSFCDbLM

and the bempp_setup.err file there:
http://pastebin.com/N1x41hYd

I hope you can help me with this.

Best regards,
Sven

**Comment by wsmigaj** [comment]
Hi Sven,

it seems that the download URL of Intel Threading Building Blocks (TBB) has changed: specifically, the HTTP protocol has been replaced by HTTPS. And the version of the ``urlgrabber`` package bundled with BEM++ doesn't handle HTTPS correctly.

You have at least two options:

1. Download TBB manually from https://www.threadingbuildingblocks.org/sites/default/files/software_releases/linux/tbb40_20120613oss_lin_0.tgz and save it as ``tbb.tgz`` in the ``installer/files`` subdirectory of the BEM++ source directory. Then rerun the BEM++ installer.

2. Alternatively,

   a. Delete or rename the ``installer/py_modules/urlgrabber`` subdirectory of the BEM++ source directory.

   b. Download the newest version of ``urlgrabber`` from http://urlgrabber.baseurl.org/download/urlgrabber-3.10.1.tar.gz, unpack it to a temporary directory, and then copy the ``urlgrabber-3.10.1/urlgrabber`` subdirectory (containing five ``*.py`` scripts) to the ``installer/py_modules/urlgrabber`` subdirectory of the BEM++ source directory.

   c. Install the ``pycurl`` package by running ``enpkg pycurl`` (or using the graphical Canopy package manager).

   d. Rerun the BEM++ installer.

Please let me know if you have any more problems.

Best regards,
Wojciech

**Comment by wsmigaj** [comment]
Actually, there is an even simpler way: open the ``installer/py_modules/urlgrabber/keepalive.py`` file and change line 350,
```
        return self._ssl_factory.create_https_connection(host)
```
to
```
        try: return self._ssl_factory.get_https_connection(host)
        except AttributeError: return HTTPSConnection(host)
```
Save the file and rerun the BEM++ installer.

Wojciech

**Comment by samschnorr** [comment]
The third version worked fine for me.
Thanks for your fast help!

I want to learn more about BEM, especially in usage with the laplace equation. But it's pretty hard to find good literature. Can u recommend me something?

**Comment by wsmigaj** [comment]
Hi Sven,

thanks for confirming the fix worked for you!

Perhaps you can have a look at some of the following books:

1. O. Steinbach, "Numerical Approximation Methods for Elliptic Boundary Value Problems: Finite and Boundary Elements".
2. S. Rjasanow, O. Steinbach, "The Fast Solution of Boundary Integral Equations".
3. Y. Liu, "Fast Multipole Boundary Element Method: Theory and Applications in Engineering" (on collocation, not Galerkin BEM, but more accessible than the previous two).
4. M. Bebendorf, "Hierarchical Matrices" (chapter 3 contains a concise description of BEM; useful if you don't want to read an entire book).

Best regards,
Wojciech

**Comment by samschnorr** [comment]
Thanks for the recommendations.

I got a little problem and don't know who to consult. Maybe u can help me a bit. I want to solve the laplace equation with a interior dirichlet problem.

**Comment by samschnorr** [comment]
Here is the source code to the problem: 
http://pastebin.com/vzgQbhgj

Following message appears when running it:

python linsentestsystem4.py 
4
Traceback (most recent call last):
  File "linsentestsystem4.py", line 97, in <module>
    lhsOp+=i
  File "/home/sven/bempp/python/bempp/core.py", line 10459, in __add__
    return _core.BoundaryOperator_float64_float64___add__(self, *args)
RuntimeError: AbstractBoundaryOperatorSum::AbstractBoundaryOperatorSum(Op1, Op2): Domains of the two terms must be equal

**Comment by wsmigaj** [comment]
Hi Sven,

if you use a separate mesh file (and space) for each connected component of the boundary of your domain, you need to form a block operator rather than a sum of operators. For example, if you had 3 domains, your left-hand side operator would be
```
[ SLP_11 SLP_12 SLP_13 ]
[ SLP_21 SLP_22 SLP_23 ]
[ SLP_31 SLP_32 SLP_33 ]
```
where ``SLP_ij`` denotes the single-layer potential boundary operator acting on functions defined on jth part of the boundary and yielding functions defined on ith part. That is, the operator constructed by
```
createLaplace3dSingleLayerBoundaryOperator(
    context, pwiseConstants_j, pwiseLinears_i, pwiseConstants_i)
```
For more information about creating and using block operators, see sections 4.2 and 4.3 in the preprint of the BEM++ paper (http://www.bempp.org/files/bempp-toms-preprint.pdf), as well as the example script ``interior_laplace_mixed.py`` mentioned in the preprint.

What is the reason that you want to construct a separate space and operator for each connected component of the boundary? Is it because you want to defined the boundary conditions separately on each component? It is true that this is rather cumbersome in BEM++ 2.0. In the upcoming version 3.0, functors used to construct grid functions can access the domain index of the element on which they are evaluated, so you can easily define a grid function equal to 1 on elements from domain (Gmsh "physical entity") 1 and equal to 0 on all other domains, for example. It shouldn't be too difficult to backport these changes to version 2.0 -- if this can be useful for you, I'll try to find time to do it over the next few days.

Best regards,
Wojciech

**Comment by samschnorr** [comment]
'What is the reason that you want to construct a separate space and operator for each connected component of the boundary?'
In my case the boundaries are spatially not connected to each other. Each boundary should be set on a different potential.

I tried to use the block operator with (full sourcecode http://pastebin.com/pxKvin4Z):
slpOp = [createLaplace3dSingleLayerBoundaryOperator(
    context, j, i[1], i[0]) for j in pwiseConstants for i in zip(pwiseConstants,pwiseLinears)]
lhsOp=createBlockedBoundaryOperator(context,slpOp)

...but it failed:

python linsentestsystem5.py 
Traceback (most recent call last):
  File "linsentestsystem5.py", line 93, in <module>
    lhsOp=createBlockedBoundaryOperator(context,slpOp)
  File "/home/sven/bempp/python/bempp/lib.py", line 2172, in createBlockedBoundaryOperator
    for j in range(len(structure[i])):
TypeError: object of type 'BoundaryOperator_float64_float64' has no len()

And i dont know how to go on from there, for example how to write the rhs correctly.

**Comment by wsmigaj** [comment]
Hi Sven,

I've created a new branch called ``feature/grid-function-domain-index`` that allows you to create a grid function dependent on the domain index (what Gmsh calls the "physical entity") of the element on which it is evaluated. This should make it easy for you to specify different potentials on different boundaries using just a single mesh file and a single standard operator (not a blocked operator).

If you are interested, please go to your BEM++ source directory and issue the following commands:
```
git pull
git checkout feature/grid-function-domain-index
cd build/bempp
cmake .
make -j3 install
```
And then have a look at the example ``python/examples/tutorial_domain_indices.py``, which shows how to solve the Laplace equation outside two spherical conductors, one set at potential +1, the other -1. Let me know if you have any questions.

Best regards,
Wojciech
