### ISSUE TITLE
Local assembly of a hypersingular Laplace operator defined on a grid segment gives incorrect results

### ISSUE THREAD

**Issue by wsmigaj** [bempp/bempp#202]
There is a problem with the local (ACA) assembly of the weak form of the Laplace (and presumably Helmholtz, too) hypersingular operator when the test and trial space is a space of piecewise linears or higher-order polynomials defined on a grid segment. This assembly method produces a matrix different from that obtained using dense assembly or global or hybrid ACA assembly. The following script demonstrates the problem.
```
#!/usr/bin/env python

# Help Python find the bempp module
import sys
sys.path.append("..")

from bempp.lib import *
import numpy as np

# Load mesh. The chosen mesh is a sphere divided into 8 domains (with indices 1
# to 8).

grid = createGridFactory().importGmshGrid(
    "triangular", "../../examples/meshes/sphere-domains.msh")

# Create quadrature strategy

accuracyOptions = createAccuracyOptions()
# Increase by 2 the order of quadrature rule used to approximate
# integrals of regular functions on pairs on elements
accuracyOptions.doubleRegular.setRelativeQuadratureOrder(2)
# Increase by 2 the order of quadrature rule used to approximate
# integrals of regular functions on single elements
accuracyOptions.singleRegular.setRelativeQuadratureOrder(2)
quadStrategy = createNumericalQuadratureStrategy(
    "float64", "float64", accuracyOptions)

# Create assembly context

assemblyOptions = createAssemblyOptions()
acaOptions = createAcaOptions()
acaOptions.mode = "local_assembly"
assemblyOptions.switchToAcaMode(acaOptions)
context = createContext(quadStrategy, assemblyOptions)

denseAssemblyOptions = createAssemblyOptions()
denseContext = createContext(quadStrategy, denseAssemblyOptions)

# Initialize grid segments on which the Dirichlet and Neumann data are defined

# Dirichlet boundary conditions will be imposed on domains 1 to 4, including
# their boundary
segmentD = (GridSegment.closedDomain(grid, 1)
            .union_(GridSegment.closedDomain(grid, 2))
            .union_(GridSegment.closedDomain(grid, 3))
            .union_(GridSegment.closedDomain(grid, 4)))
# Neumann boundary conditions will be imposed on the rest of the grid
segmentN = segmentD.complement()

# Initialize spaces

pwiseConstants = createPiecewiseConstantScalarSpace(context, grid)
pwiseConstantsD = createPiecewiseConstantScalarSpace(context, grid, segmentD)
pwiseConstantsN = createPiecewiseConstantScalarSpace(context, grid, segmentN)
pwiseLinears = createPiecewiseLinearContinuousScalarSpace(context, grid)
pwiseLinearsD = createPiecewiseLinearContinuousScalarSpace(
    context, grid, segmentD)
pwiseLinearsN = createPiecewiseLinearContinuousScalarSpace(
    context, grid, segmentN)

# Construct elementary operators

slpOpDD = createLaplace3dSingleLayerBoundaryOperator(
    context, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
slpOpNN = createLaplace3dSingleLayerBoundaryOperator(
    context, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
slpOp = createLaplace3dSingleLayerBoundaryOperator(
    context, pwiseLinears, pwiseConstants, pwiseLinears)
hypOpDD = createLaplace3dHypersingularBoundaryOperator(
    context, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
hypOpNN = createLaplace3dHypersingularBoundaryOperator(
    context, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
hypOp = createLaplace3dHypersingularBoundaryOperator(
    context, pwiseLinears, pwiseConstants, pwiseLinears)

denseSlpOpDD = createLaplace3dSingleLayerBoundaryOperator(
    denseContext, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
denseSlpOpNN = createLaplace3dSingleLayerBoundaryOperator(
    denseContext, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
denseSlpOp = createLaplace3dSingleLayerBoundaryOperator(
    denseContext, pwiseLinears, pwiseConstants, pwiseLinears)
denseHypOpDD = createLaplace3dHypersingularBoundaryOperator(
    denseContext, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
denseHypOpNN = createLaplace3dHypersingularBoundaryOperator(
    denseContext, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
denseHypOp = createLaplace3dHypersingularBoundaryOperator(
    denseContext, pwiseLinears, pwiseConstants, pwiseLinears)

op = slpOpDD.weakForm().asMatrix()
denseOp = denseSlpOpDD.weakForm().asMatrix()
print "error slpOpDD:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)

op = slpOpNN.weakForm().asMatrix()
denseOp = denseSlpOpNN.weakForm().asMatrix()
print "error slpOpNN:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)

op = slpOp.weakForm().asMatrix()
denseOp = denseSlpOp.weakForm().asMatrix()
print "error slpOp:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)

op = hypOpDD.weakForm().asMatrix()
denseOp = denseHypOpDD.weakForm().asMatrix()
print "error hypOpDD:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)

op = hypOpNN.weakForm().asMatrix()
denseOp = denseHypOpNN.weakForm().asMatrix()
print "error hypOpNN:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)

op = hypOp.weakForm().asMatrix()
denseOp = denseHypOp.weakForm().asMatrix()
print "error hypOp:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
```
The script prints the Frobenius norm of the difference between the matrices produced by dense assembly and by local ACA assembly of the weak form of the single-layer potential boundary operator and the hypersingular operator, defined first on two grid segments and then the whole grid. The results are normalised to the norm of the matrix generated using dense assembly. The output is
```
error slpOpDD: 1.16042799025e-05
error slpOpNN: 1.0325641097e-05
error slpOp: 1.55981745694e-05
error hypOpDD: 0.058535162788
error hypOpNN: 0.0606415035871
error hypOp: 2.3353401319e-05
```
That is, there are no problems with the single-layer potential operator or with the hypersingular operator defined on the whole grid, but the weak forms of the latter operator defined on grid segments are wrong.

For hypersingular operators, the local assembly method relies on the expansion of the surface curl of the basis functions of the test and trial space in a space spanned by discontinuous functions, obtained by calling ``Space::discontinuousSpace()``. The current implementation of ``PiecewiseLinearContinuousScalarSpace::discontinuousSpace()`` returns a space whose basis functions are restrictions of the basis functions of the original space to individual elements. This unfortunately means that the curl of a basis function of ``PiecewiseLinearContinuousScalarSpace`` associated with a vertex lying at the border of a grid segment is not representable in the "discontinuous space". Same holds for higher-order polynomial spaces.

One solution would be change the implementation of ``PiecewiseLinearContinuousScalarSpace::discontinuousSpace()`` so that it would return a space containing the full set of local basis functions living on each element on which at least one basis function of the "continuous space" is nonzero. Incidentally, if ``PiecewiseLinearContinuousScalarSpace::discontinuousSpace()`` is redefined so that the returned space is defined on the whole grid, the problem disappears (though of course this is an inefficient solution).

Timo, do you have any thoughts on that? Can you think of any applications of ``discontinuousSpace()`` other than local ACA assembly? Could be affected by a change of the returned space?

Best regards,
Wojtek

**Comment by tbetcke** [comment]
Hi Wojtek,

thanks for discovering this. I think that your solution should have no side
effect. Other than local ACA assembly I am not aware of any place where
this is used. I am generally a bit uneasy about the current gridsegment
implementation. It is quite volatile in the sense that it makes
implementations of spaces very complicated. There is the module
dune-multidomaingrid, which allows to create subgrids from existing grids,
which are grid objects in their own right.
Would this make the implementation of grid segments easier? We would just
return a subgrid and define standard spaces on the subgrid.

Next week I want to start on updating our Grids to Alugrid and remove all
our Dune patches. This might make a good opportunity to also revisit grid
segments.

What do you think?

Best wishes

Timo


On 30 January 2015 at 00:03, Wojciech Śmigaj <notifications@github.com>
wrote:

> There is a problem with the local (ACA) assembly of the weak form of the
> Laplace (and presumably Helmholtz, too) hypersingular operator when the
> test and trial space is a space of piecewise linears or higher-order
> polynomials defined on a grid segment. This assembly method produces a
> matrix different from that obtained using dense assembly or global or
> hybrid ACA assembly. The following script demonstrates the problem.
>
> #!/usr/bin/env python
>
> # Help Python find the bempp module
> import sys
> sys.path.append("..")
>
> from bempp.lib import *
> import numpy as np
>
> # Load mesh. The chosen mesh is a sphere divided into 8 domains (with indices 1
> # to 8).
>
> grid = createGridFactory().importGmshGrid(
>     "triangular", "../../examples/meshes/sphere-domains.msh")
>
> # Create quadrature strategy
>
> accuracyOptions = createAccuracyOptions()
> # Increase by 2 the order of quadrature rule used to approximate
> # integrals of regular functions on pairs on elements
> accuracyOptions.doubleRegular.setRelativeQuadratureOrder(2)
> # Increase by 2 the order of quadrature rule used to approximate
> # integrals of regular functions on single elements
> accuracyOptions.singleRegular.setRelativeQuadratureOrder(2)
> quadStrategy = createNumericalQuadratureStrategy(
>     "float64", "float64", accuracyOptions)
>
> # Create assembly context
>
> assemblyOptions = createAssemblyOptions()
> acaOptions = createAcaOptions()
> acaOptions.mode = "local_assembly"
> assemblyOptions.switchToAcaMode(acaOptions)
> context = createContext(quadStrategy, assemblyOptions)
>
> denseAssemblyOptions = createAssemblyOptions()
> denseContext = createContext(quadStrategy, denseAssemblyOptions)
>
> # Initialize grid segments on which the Dirichlet and Neumann data are defined
>
> # Dirichlet boundary conditions will be imposed on domains 1 to 4, including
> # their boundary
> segmentD = (GridSegment.closedDomain(grid, 1)
>             .union_(GridSegment.closedDomain(grid, 2))
>             .union_(GridSegment.closedDomain(grid, 3))
>             .union_(GridSegment.closedDomain(grid, 4)))
> # Neumann boundary conditions will be imposed on the rest of the grid
> segmentN = segmentD.complement()
>
> # Initialize spaces
>
> pwiseConstants = createPiecewiseConstantScalarSpace(context, grid)
> pwiseConstantsD = createPiecewiseConstantScalarSpace(context, grid, segmentD)
> pwiseConstantsN = createPiecewiseConstantScalarSpace(context, grid, segmentN)
> pwiseLinears = createPiecewiseLinearContinuousScalarSpace(context, grid)
> pwiseLinearsD = createPiecewiseLinearContinuousScalarSpace(
>     context, grid, segmentD)
> pwiseLinearsN = createPiecewiseLinearContinuousScalarSpace(
>     context, grid, segmentN)
>
> # Construct elementary operators
>
> slpOpDD = createLaplace3dSingleLayerBoundaryOperator(
>     context, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
> slpOpNN = createLaplace3dSingleLayerBoundaryOperator(
>     context, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
> slpOp = createLaplace3dSingleLayerBoundaryOperator(
>     context, pwiseLinears, pwiseConstants, pwiseLinears)
> hypOpDD = createLaplace3dHypersingularBoundaryOperator(
>     context, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
> hypOpNN = createLaplace3dHypersingularBoundaryOperator(
>     context, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
> hypOp = createLaplace3dHypersingularBoundaryOperator(
>     context, pwiseLinears, pwiseConstants, pwiseLinears)
>
> denseSlpOpDD = createLaplace3dSingleLayerBoundaryOperator(
>     denseContext, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
> denseSlpOpNN = createLaplace3dSingleLayerBoundaryOperator(
>     denseContext, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
> denseSlpOp = createLaplace3dSingleLayerBoundaryOperator(
>     denseContext, pwiseLinears, pwiseConstants, pwiseLinears)
> denseHypOpDD = createLaplace3dHypersingularBoundaryOperator(
>     denseContext, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
> denseHypOpNN = createLaplace3dHypersingularBoundaryOperator(
>     denseContext, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
> denseHypOp = createLaplace3dHypersingularBoundaryOperator(
>     denseContext, pwiseLinears, pwiseConstants, pwiseLinears)
>
> op = slpOpDD.weakForm().asMatrix()
> denseOp = denseSlpOpDD.weakForm().asMatrix()
> print "error slpOpDD:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>
> op = slpOpNN.weakForm().asMatrix()
> denseOp = denseSlpOpNN.weakForm().asMatrix()
> print "error slpOpNN:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>
> op = slpOp.weakForm().asMatrix()
> denseOp = denseSlpOp.weakForm().asMatrix()
> print "error slpOp:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>
> op = hypOpDD.weakForm().asMatrix()
> denseOp = denseHypOpDD.weakForm().asMatrix()
> print "error hypOpDD:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>
> op = hypOpNN.weakForm().asMatrix()
> denseOp = denseHypOpNN.weakForm().asMatrix()
> print "error hypOpNN:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>
> op = hypOp.weakForm().asMatrix()
> denseOp = denseHypOp.weakForm().asMatrix()
> print "error hypOp:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>
> The script prints the Frobenius norm of the difference between the
> matrices produced by dense assembly and by local ACA assembly of the weak
> form of the single-layer potential boundary operator and the hypersingular
> operator, defined first on two grid segments and then the whole grid. The
> results are normalised to the norm of the matrix generated using dense
> assembly. The output is
>
> error slpOpDD: 1.16042799025e-05
> error slpOpNN: 1.0325641097e-05
> error slpOp: 1.55981745694e-05
> error hypOpDD: 0.058535162788
> error hypOpNN: 0.0606415035871
> error hypOp: 2.3353401319e-05
>
> That is, there are no problems with the single-layer potential operator or
> with the hypersingular operator defined on the whole grid, but the weak
> forms of the latter operator defined on grid segments are wrong.
>
> For hypersingular operators, the local assembly method relies on the
> expansion of the surface curl of the basis functions of the test and trial
> space in a space spanned by discontinuous functions, obtained by calling
> Space::discontinuousSpace(). The current implementation of
> PiecewiseLinearContinuousScalarSpace::discontinuousSpace() returns a
> space whose basis functions are restrictions of the basis functions of the
> original space to individual elements. This unfortunately means that the
> curl of a basis function of PiecewiseLinearContinuousScalarSpace
> associated with a vertex lying at the border of a grid segment is not
> representable in the "discontinuous space". Same holds for higher-order
> polynomial spaces.
>
> One solution would be change the implementation of
> PiecewiseLinearContinuousScalarSpace::discontinuousSpace() so that it
> would return a space containing the full set of local basis functions
> living on each element on which at least one basis function of the
> "continuous space" is nonzero. Incidentally, if
> PiecewiseLinearContinuousScalarSpace::discontinuousSpace() is redefined
> so that the returned space is defined on the whole grid, the problem
> disappears (though of course this is an inefficient solution).
>
> Timo, do you have any thoughts on that? Can you think of any applications
> of discontinuousSpace() other than local ACA assembly? Could be affected
> by a change of the returned space?
>
> Best regards,
> Wojtek
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/202>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by tbetcke** [comment]
Small addition. The dune-subgrid module would also be possible.
Best wishes

Timo

On 31 January 2015 at 17:28, Timo Betcke <timo.betcke@gmail.com> wrote:

> Hi Wojtek,
>
> thanks for discovering this. I think that your solution should have no
> side effect. Other than local ACA assembly I am not aware of any place
> where this is used. I am generally a bit uneasy about the current
> gridsegment implementation. It is quite volatile in the sense that it makes
> implementations of spaces very complicated. There is the module
> dune-multidomaingrid, which allows to create subgrids from existing grids,
> which are grid objects in their own right.
> Would this make the implementation of grid segments easier? We would just
> return a subgrid and define standard spaces on the subgrid.
>
> Next week I want to start on updating our Grids to Alugrid and remove all
> our Dune patches. This might make a good opportunity to also revisit grid
> segments.
>
> What do you think?
>
> Best wishes
>
> Timo
>
>
> On 30 January 2015 at 00:03, Wojciech Śmigaj <notifications@github.com>
> wrote:
>
>> There is a problem with the local (ACA) assembly of the weak form of the
>> Laplace (and presumably Helmholtz, too) hypersingular operator when the
>> test and trial space is a space of piecewise linears or higher-order
>> polynomials defined on a grid segment. This assembly method produces a
>> matrix different from that obtained using dense assembly or global or
>> hybrid ACA assembly. The following script demonstrates the problem.
>>
>> #!/usr/bin/env python
>>
>> # Help Python find the bempp module
>> import sys
>> sys.path.append("..")
>>
>> from bempp.lib import *
>> import numpy as np
>>
>> # Load mesh. The chosen mesh is a sphere divided into 8 domains (with indices 1
>> # to 8).
>>
>> grid = createGridFactory().importGmshGrid(
>>     "triangular", "../../examples/meshes/sphere-domains.msh")
>>
>> # Create quadrature strategy
>>
>> accuracyOptions = createAccuracyOptions()
>> # Increase by 2 the order of quadrature rule used to approximate
>> # integrals of regular functions on pairs on elements
>> accuracyOptions.doubleRegular.setRelativeQuadratureOrder(2)
>> # Increase by 2 the order of quadrature rule used to approximate
>> # integrals of regular functions on single elements
>> accuracyOptions.singleRegular.setRelativeQuadratureOrder(2)
>> quadStrategy = createNumericalQuadratureStrategy(
>>     "float64", "float64", accuracyOptions)
>>
>> # Create assembly context
>>
>> assemblyOptions = createAssemblyOptions()
>> acaOptions = createAcaOptions()
>> acaOptions.mode = "local_assembly"
>> assemblyOptions.switchToAcaMode(acaOptions)
>> context = createContext(quadStrategy, assemblyOptions)
>>
>> denseAssemblyOptions = createAssemblyOptions()
>> denseContext = createContext(quadStrategy, denseAssemblyOptions)
>>
>> # Initialize grid segments on which the Dirichlet and Neumann data are defined
>>
>> # Dirichlet boundary conditions will be imposed on domains 1 to 4, including
>> # their boundary
>> segmentD = (GridSegment.closedDomain(grid, 1)
>>             .union_(GridSegment.closedDomain(grid, 2))
>>             .union_(GridSegment.closedDomain(grid, 3))
>>             .union_(GridSegment.closedDomain(grid, 4)))
>> # Neumann boundary conditions will be imposed on the rest of the grid
>> segmentN = segmentD.complement()
>>
>> # Initialize spaces
>>
>> pwiseConstants = createPiecewiseConstantScalarSpace(context, grid)
>> pwiseConstantsD = createPiecewiseConstantScalarSpace(context, grid, segmentD)
>> pwiseConstantsN = createPiecewiseConstantScalarSpace(context, grid, segmentN)
>> pwiseLinears = createPiecewiseLinearContinuousScalarSpace(context, grid)
>> pwiseLinearsD = createPiecewiseLinearContinuousScalarSpace(
>>     context, grid, segmentD)
>> pwiseLinearsN = createPiecewiseLinearContinuousScalarSpace(
>>     context, grid, segmentN)
>>
>> # Construct elementary operators
>>
>> slpOpDD = createLaplace3dSingleLayerBoundaryOperator(
>>     context, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
>> slpOpNN = createLaplace3dSingleLayerBoundaryOperator(
>>     context, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
>> slpOp = createLaplace3dSingleLayerBoundaryOperator(
>>     context, pwiseLinears, pwiseConstants, pwiseLinears)
>> hypOpDD = createLaplace3dHypersingularBoundaryOperator(
>>     context, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
>> hypOpNN = createLaplace3dHypersingularBoundaryOperator(
>>     context, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
>> hypOp = createLaplace3dHypersingularBoundaryOperator(
>>     context, pwiseLinears, pwiseConstants, pwiseLinears)
>>
>> denseSlpOpDD = createLaplace3dSingleLayerBoundaryOperator(
>>     denseContext, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
>> denseSlpOpNN = createLaplace3dSingleLayerBoundaryOperator(
>>     denseContext, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
>> denseSlpOp = createLaplace3dSingleLayerBoundaryOperator(
>>     denseContext, pwiseLinears, pwiseConstants, pwiseLinears)
>> denseHypOpDD = createLaplace3dHypersingularBoundaryOperator(
>>     denseContext, pwiseLinearsD, pwiseConstantsD, pwiseLinearsD)
>> denseHypOpNN = createLaplace3dHypersingularBoundaryOperator(
>>     denseContext, pwiseLinearsN, pwiseConstantsN, pwiseLinearsN)
>> denseHypOp = createLaplace3dHypersingularBoundaryOperator(
>>     denseContext, pwiseLinears, pwiseConstants, pwiseLinears)
>>
>> op = slpOpDD.weakForm().asMatrix()
>> denseOp = denseSlpOpDD.weakForm().asMatrix()
>> print "error slpOpDD:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>>
>> op = slpOpNN.weakForm().asMatrix()
>> denseOp = denseSlpOpNN.weakForm().asMatrix()
>> print "error slpOpNN:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>>
>> op = slpOp.weakForm().asMatrix()
>> denseOp = denseSlpOp.weakForm().asMatrix()
>> print "error slpOp:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>>
>> op = hypOpDD.weakForm().asMatrix()
>> denseOp = denseHypOpDD.weakForm().asMatrix()
>> print "error hypOpDD:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>>
>> op = hypOpNN.weakForm().asMatrix()
>> denseOp = denseHypOpNN.weakForm().asMatrix()
>> print "error hypOpNN:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>>
>> op = hypOp.weakForm().asMatrix()
>> denseOp = denseHypOp.weakForm().asMatrix()
>> print "error hypOp:", np.linalg.norm((op - denseOp)) / np.linalg.norm(denseOp)
>>
>> The script prints the Frobenius norm of the difference between the
>> matrices produced by dense assembly and by local ACA assembly of the weak
>> form of the single-layer potential boundary operator and the hypersingular
>> operator, defined first on two grid segments and then the whole grid. The
>> results are normalised to the norm of the matrix generated using dense
>> assembly. The output is
>>
>> error slpOpDD: 1.16042799025e-05
>> error slpOpNN: 1.0325641097e-05
>> error slpOp: 1.55981745694e-05
>> error hypOpDD: 0.058535162788
>> error hypOpNN: 0.0606415035871
>> error hypOp: 2.3353401319e-05
>>
>> That is, there are no problems with the single-layer potential operator
>> or with the hypersingular operator defined on the whole grid, but the weak
>> forms of the latter operator defined on grid segments are wrong.
>>
>> For hypersingular operators, the local assembly method relies on the
>> expansion of the surface curl of the basis functions of the test and trial
>> space in a space spanned by discontinuous functions, obtained by calling
>> Space::discontinuousSpace(). The current implementation of
>> PiecewiseLinearContinuousScalarSpace::discontinuousSpace() returns a
>> space whose basis functions are restrictions of the basis functions of the
>> original space to individual elements. This unfortunately means that the
>> curl of a basis function of PiecewiseLinearContinuousScalarSpace
>> associated with a vertex lying at the border of a grid segment is not
>> representable in the "discontinuous space". Same holds for higher-order
>> polynomial spaces.
>>
>> One solution would be change the implementation of
>> PiecewiseLinearContinuousScalarSpace::discontinuousSpace() so that it
>> would return a space containing the full set of local basis functions
>> living on each element on which at least one basis function of the
>> "continuous space" is nonzero. Incidentally, if
>> PiecewiseLinearContinuousScalarSpace::discontinuousSpace() is redefined
>> so that the returned space is defined on the whole grid, the problem
>> disappears (though of course this is an inefficient solution).
>>
>> Timo, do you have any thoughts on that? Can you think of any applications
>> of discontinuousSpace() other than local ACA assembly? Could be affected
>> by a change of the returned space?
>>
>> Best regards,
>> Wojtek
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bempp/bempp/issues/202>.
>>
>
>
>
> --
> Dr. Timo Betcke
> Reader in Mathematics
> University College London
> Department of Mathematics
> E-Mail: t.betcke@ucl.ac.uk
> Tel.: +44 (0) 20-3108-4068
> Fax.: +44 (0) 20-7383-5519
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by wsmigaj** [comment]
Hi Timo,

thanks, then I will implement the proposed solution in the near future (I hope there won't be any unforeseen difficulties).

About grid segments: I agree that they make the assignment of global degrees of freedom in space implementations complicated, but I don't think the use of either dune-subgrid or dune-multidomaingrid will reduce this complexity.

As far as I understand from the papers describing these libraries, their interfaces expect you to define a domain by marking a set of entities of codimension 0; the resulting metagrid consists then of these entities (elements) along with all their vertices and edges (and faces, for volume grids). Thus, for example, a space of piecewise linears defined "naturally" on such a metagrid would be the span of the hat functions associated with all the vertices belonging to the selected elements; crucially, they would also be truncated to these elements, as in the following figure:
![case1](https://cloud.githubusercontent.com/assets/1110609/5989833/ec65d6f6-a98c-11e4-9036-515a14f132fc.png)
Here, the black dots are the vertices of the original grid; elements belonging to the grid segments are marked in red; and the green "hats" represent the basis functions of the space that would be constructed, were a ``PiecewiseLinearContinuousScalarSpace`` be given the metagrid defined on the red elements.

The problem is that usually this is not the space we want. Rather, we want the space spanned by the non-truncated (continuous) hat functions associated with all the vertices of the grid segment, possibly extending on the part of the original grid not belonging to the segment:
![case2](https://cloud.githubusercontent.com/assets/1110609/5989832/ec4817ce-a98c-11e4-93a9-4f347678d334.png)
Or the space spanned by the hat functions associated with the vertices lying in the interior of the grid segment:
![case3](https://cloud.githubusercontent.com/assets/1110609/5989831/ec33d200-a98c-11e4-9103-1bc8eeaf2ff6.png)
This is where the complications in the implementation of spaces come from. They do not fit in the framework of metagrids defined solely by the codimension-0 entities; therefore if dune-multidomaingrid or dune-subgrid were to be used, the two latter cases shown above would still need to be handled "manually" in the space classes on a case-by-case basis, and I do not think the implementation would be any easier.

Best regards,
Wojtek

**Comment by wsmigaj** [comment]
(Update: I reworded the last paragraph of the previous post; I hope this makes it clearer.)

**Comment by tbetcke** [comment]
Hi Wojtek,

thanks for the clarification. Not sure what one could do. For standard
formulations of mixed problems we need this imbedding that you just
described.
However, in particular for higher order polynomial spaces it is a massive
pain to implement. I will need to think about this again as I was hoping to
eventually get rid of these complicated initialisation codes for the spaces.

Best wishes

Timo




On 31 January 2015 at 21:13, Wojciech Śmigaj <notifications@github.com>
wrote:

> (Update: I reworded the last paragraph of the previous post; I hope this
> makes it clearer.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/202#issuecomment-72336939>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by wsmigaj** [comment]
Hi Timo,

maybe the code would be simpler if the spaces first enumerated the global DOFs as if they were defined on the whole grid, and then removed the DOFs located on entities (elements, edges or vertices -- depending on the space) not belonging to the grid segment?

This would have some performance impact, but perhaps not a big one.

Best regards,
Wojtek
