### ISSUE TITLE
Error when running python example tutorial_dirichlet.py

### ISSUE THREAD

**Issue by jyhou** [bempp/bempp#204]
Dear BEM++ developers,

I've installed BEM++ on Ubuntu-14.04.1 on a virtual box. But I got an error when runnning BEM++ python example tutorial_dirichlet.py. My commands and the error message are shown below.

jyhou@jyhou-VirtualBox:~/Documents/research/BEM/bempp/python/examples$ python tutorial_dirichlet.py 
Traceback (most recent call last):
  File "tutorial_dirichlet.py", line 7, in <module>
    from bempp.lib import *
  File "../bempp/__init__.py", line 1, in <module>
    from core import *
ImportError: No module named core

I used the EPD version epd-7.3-2-rh5-x86_64 to install BEM++ (and I used EPD python as default). I checked the folder ~/Documents/research/BEM/bempp/python/bempp, and there is no _core.so in it. Here is also my bempp_setup.cfg file:

# This file controls the build settings for BEM++.
# You need to at least do the following.

# Specify the architecture and prefix in the [Main]
# section.

# Choose a BLAS and Lapack library. Enable either MKL (recommended)
# or choose a BLAS and Lapack library manually. Please see the 
# README for recommended options.

# It is highly recommended to download and enable AHMED in the [AHMED]
# section. This enables the H-Matrix algebra for the library and 
# allows to solve significantly larger problems than with a standard
# dense matrix BEM.

[Main]

# Specify your system architecture. Allowed values: intel64 (for
# 64-bit systems), ia32 (for 32-bit systems), Example:

architecture=intel64

# By default BEM++ and its dependencies will be built in the
# subdirectory "build" of the BEM++ source directory. You can override
# this by setting the option below. Example:

# build_dir=~/src/bempp-build

# Specify the prefix of the installation directory.  BEM++ and its
# dependencies will be installed in prefix/bempp. Example:

prefix=~

# It is highly recommended to adapt the number of threads used to 
# build the library to the number of underlying CPU cores. A good rule 
# of thumb is to choose build_jobs = 1.5*(number of cores), e.g. for 
# a dual-core system choose build_jobs=3. This significantly speeds 
# up the compilation process.

build_jobs=2

# The following options control the compilers and compiler flags.
# You can override the options for specific libraries by setting
# these options within the corresponding section.

# C Compiler
# cc = gcc

# C++ Compiler
# cxx = g++

# C Compiler flags
# cflags =

# C++ Compiler flags
#  cxxflags =

# Optimization flags
# optflags = -O3 -march=native (Default on Linux)
# optflags = -O3 -march=core2 (Default on Mac)

[Bempp]

# Specify whether the installer should compile BEM++ straight after
# installing its dependencies. Normally this should be set to 'yes';
# set to 'no' only if you want to change some BEM++ compilation
# options manually. Example:

build=yes

[MKL]

# If you want to use BLAS and LAPACK from Intel MKL, uncomment the
# following line

enable_mkl=yes

# and specify where the MKL libraries can be found.

# If the NumPy package in your Python distribution is linked against
# MKL (for example, you use Enthought Python), uncomment the following
# line to have the BEM++ installer use the same MKL libraries as
# NumPy.

source=like_numpy

# Otherwise, you need to specify manually the location of MKL on your disk.
# Uncomment the following line

# source=installed

# and specify the directories containing the MKL libraries (such
# as libmkl_core and libiomp5) in the following variable. You may
# specify several directories at once by separating them with
# semicolons. Example:

# dir=/opt/intel/mkl/lib/intel64;/opt/intel/lib/intel64

# You can also customize the list of MKL libraries to link against
# by editing the following variable. The default setting below
# (-lmkl_rt) should work for MKL 10.3 or newer. In case of
# problems use the Intel MKL Link Line Advisor
# (http://software.intel.com/en-us/articles/intel-mkl-link-line-advisor)
# to find the setting appropriate for your configuration. You may
# specify several libraries at once by separating them with
# semicolons.

lib=-lmkl_rt

[BLAS]

# If you want to use another BLAS library than Intel MKL, specify its
# location in the following variable. You may specify several paths at
# once by separating them with semicolons. Example:

# lib=/usr/lib/libblas.so

[LAPACK]

# If you want to use another BLAS library than Intel MKL, specify its
# location in the following variable. You may specify several paths at
# once by separating them with semicolons. Example:

# lib=/usr/lib/liblapack.so

[AHMED]

# Uncomment the following line if you have downloaded the AHMED
# library by Mario Bebendorf from
# http://bebendorf.ins.uni-bonn.de/AHMED.html and you want to compile
# and install it along with BEM++. This library enables BEM++ to use
# the adaptive cross approximation algorithm to speed up calculations.

# enable_ahmed=yes

# If you have set enable_ahmed to yes, specify the path to the archive
# file with the sources of AHMED. Example:

# file_name=~/Downloads/AHMED-1.0.tar.gz

# Use this section to override compiler settings for AHMED

[Boost]
# Use this section to override compiler settings for Boost

[Dune]
# Use this section to override compiler settings for Dune

[Swig]
# Use this section to override compiler settings for Swig

[Trilinos]
# Use this section to override compiler settings for Trilinos

[MPI]

# Enable MPI support and specify the MPI include directory and MPI 
# libraries here. If you use MPI compier wrappers (e.g. mpicxxx and mpicc)
# you just have to uncomment enable_mpi = true to enable MPI support. If
# compiler wrappers are not used then additionally the mpi include directory
# and mpi libraries need to be specified. The given example configuration is
# for OpenMPI. Please note that this is experimental and currently only used
# to compile the PyTrilinos solvers with MPI support.

# enable_mpi = true
# mpi_cxx_libs = -L/usr/local/openmpi/lib -lmpi_cxx -lmpi
# mpi_include_dir = /usr/local/openmpi/include

[Python]

# You do not normally need to edit this section. However, if the BEM++
# installer cannot find your Python include directory (the directory
# containing Python.h) or runtime library (libpython), you can specify
# their locations explicitly here. Examples:

# include_dir=/home/jyhou/Documents/research/mypython/include/python2.7
# lib=/home/jyhou/Documents/research/mypython/lib/libpython2.7.so

# include_dir=/usr/include/python2.7
# lib=/usr/lib/libpython2.7.so

Can you give me some advice on this problem?  Thank you very much!!!

Best regards,
Jiangyi

**Comment by wsmigaj** [comment]
Hi Jiangyi,

you need to run the Python examples from either the BEM++ build or install directory -- not the source directory, as you're currently doing. It seems that your installation directory is ``~`` -- so go to ``~/bempp/python/examples`` and run ``python tutorial_dirichlet.py`` from there.

As you have installed BEM++ without AHMED, you will also need to comment out the line
```
assemblyOptions.switchToAcaMode(createAcaOptions())
```
in the script to make BEM++ use the dense assembly mode rather than the adaptive cross approximation (ACA) mode, which is only available with AHMED.

Best regards,
Wojciech

**Comment by jyhou** [comment]
Hi wsmigaj,

Thanks for the help! I followed your instructions but got a new error message:

jyhou@jyhou-VirtualBox:~/bempp/python/examples$ python tutorial_dirichlet.py 
Traceback (most recent call last):
  File "tutorial_dirichlet.py", line 7, in <module>
    from bempp.lib import *
  File "../bempp/__init__.py", line 1, in <module>
    from core import *
  File "../bempp/core.py", line 26, in <module>
    _core = swig_import_helper()
  File "../bempp/core.py", line 22, in swig_import_helper
    _mod = imp.load_module('_core', fp, pathname, description)
ImportError: libteuchoscore.so: cannot open shared object file: No such file or directory

I also tried the instructions of using the python interface from the installation website, but got: 

ImportError: No module named bempp.lib

Does that mean I haven't installed the bem++ correctly? Could you give me some more advice? 

Thank you!
Jiangyi

**Comment by jyhou** [comment]
Hi Wojciech,

 

Thanks for the help! I followed your instructions but got a new error message:

 

jyhou@jyhou-VirtualBox:~/bempp/python/examples$ python tutorial_dirichlet.py 

Traceback (most recent call last):

File "tutorial_dirichlet.py", line 7, in 

from bempp.lib import *

File "../bempp/init.py", line 1, in 

from core import *

File "../bempp/core.py", line 26, in 

_core = swig_import_helper()

File "../bempp/core.py", line 22, in swig_import_helper

_mod = imp.load_module('_core', fp, pathname, description)

ImportError: libteuchoscore.so: cannot open shared object file: No such file or directory

 

I also tried the instructions of using the python interface from the installation website, but got:

 

ImportError: No module named bempp.lib

 

Does that imply I haven't installed the bem++ correctly? Could you give me some more advice?

 

Thank you!

Jiangyi

**Comment by wsmigaj** [comment]
Hi Jiangyi,

I don't know what is the cause of your problem, but I'll try to reproduce it on a Ubuntu virtual machine in the evening. I'll keep you updated.

Best regards,
Wojciech

**Comment by jyhou** [comment]
Thank you very much, Wojciech!
Jiangyi

**Comment by wsmigaj** [comment]
Dear Jiangyi,

I can't reproduce the issue you're having: I was able to install BEM++ on a 64-bit Ubuntu 14.04 virtual machine with EPD 7.3 using your configuration file without any problems, and running ``python tutorial_dirichlet.py`` from ``~/bempp/python/examples`` produces the expected output.

Do you have a ``libteuchoscore.so`` file in the ``~/bempp/lib`` directory? If you don't, something has indeed gone wrong during the installation. Did your installer produce any error messages at all?

Maybe you could try installing BEM++ again from scratch (delete the source and installation directories beforehand). Save the output produced by the ``bempp_setup.py`` script, and if the problem occurs again, send us this output.

Best regards,
Wojciech

**Comment by jyhou** [comment]
Hi Wojciech,

I do have a libteuchoscore.so file in the ~/bempp/lib directory.
But I forgot to tell that I had manually installed LAPACK and BLAS before I started to install BEM++. (Really sorry about this.) And I copied the liblapck.a, librefblas.a and libtmglib.a into the /usr/lib directory and the /usr/local/lib directory. Would that be the reason that caused all these issues? Should I just remove that and then reinstall BEM++? Also I set the EPD python as my default python by removing the original python linking file and generating a new link to the EPD python. Would that be supposed or not?
Thanks so very much for the help! !!

Best regards,
Jiangyi

**Comment by wsmigaj** [comment]
Hello,

EPD (at least the academic version) comes with MKL, so it doesn't need any other BLAS or LAPACK. But having a version of BLAS or LAPACK in ``/usr/bin`` etc. doesn't do any harm. I wouldn't make EPD the default Python by changing the symbolic links, however; instead, I'd prepend the path to the ``bin`` subdirectory in the EPD installation tree to the beginning of the PATH variable. This will ensure that _all_ Python-related executables/scripts, e.g. ``ipython``, ``python-config`` or ``swig`` (and not just the Python interpreter), are found in the EPD directory rather than in ``/usr/bin``.

Best regards,
Wojciech
