### ISSUE TITLE
features/eigen3 branch: missing eigen_fwd.hpp file

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#207]
Hello,

@tbetcke did you forget to commit the eigen_fwd.hpp in the features/eigen3 branch? 

Regards,
Thomas

**Comment by tbetcke** [comment]
Thanks. Will do. The branch is not yet usable. I hope to finish it by the
end of this week or early next week. The goal is to move everything to
eigen and remove Armadillo and Trillions. This will allow us to build BEM++
without explicit BLAS dependency, making installation a lot easier.

On 7 April 2015 at 09:34, Thomas Hisch <notifications@github.com> wrote:

> Hello,
>
> @tbetcke <https://github.com/tbetcke> did you forget to commit the
> eigen_fwd.hpp in the features/eigen3 branch?
>
> Regards,
> Thomas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/207>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by thisch** [comment]
I wanted to test the new Maxwell operators, therefore I checked out the eigen3 branch. 

BTW do you plan to create a new minor release with support for Maxwell operators or do I have to wait till 3.0?

**Comment by tbetcke** [comment]
Hi Thomas,

all Maxwell operators, potentials and far-field operators are contained in the development branch. A corresponding IPython tutorial (still needs small improvements) is available at:

https://github.com/bempp/tutorials/blob/master/notebooks/maxwell_screen/notebook.ipynb

Let me know if everything works fine for you.

Once the eigen3 transition is completed we will push out the next minor release. There will be frequent minor releases now.

Best wishes

Timo

**Comment by thisch** [comment]
I remember that I had problems with the Maxwell and the 'development' branch. I will try to test those branches again in the coming days.

**Comment by thisch** [comment]
Ther eigen_fwd.hpp error seems to be gone (features/eigen3 branch). Now I get 
```
[ 51%] Building CXX object tests/unit/CMakeFiles/manager_fixture.dir/grid/simple_triangular_grid_manager.cpp.o
In file included from /tmp/bempptest/bempp/build/include/bempp/grid/grid_factory.hpp:27:0,
                 from /tmp/bempptest/bempp/tests/unit/assembly/create_regular_grid.cpp:22:
/tmp/bempptest/bempp/build/include/bempp/grid/../common/eigen_support.hpp:4:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
```

**Comment by thisch** [comment]
As ``Eigen`` is also required if the Fenics stuff was not enabled, 'lookup_package(Eigen3 REQUIRED)' needs to be moved from `` cmake/BemppFenicsDependencies.cmake`` to ``cmake/BemppFindDependencies.cmake``

**Comment by thisch** [comment]
Now I get

```
/tmp/bempptest/bempp/lib/assembly/sparse_inverse.cpp: In function ‘boost::shared_ptr<Eigen::SparseMatrix<double> > Bempp::sparseInverse(const RealSparseMatrix&)’:
/tmp/bempptest/bempp/lib/assembly/sparse_inverse.cpp:37:60: error: ‘RealSparseMatr’ was not declared in this scope
   shared_ptr<RealSparseMatrix> result = boost::make_shared<RealSparseMatr>(
                                                            ^
/tmp/bempptest/bempp/lib/assembly/sparse_inverse.cpp:38:24: error: no matching function for call to ‘make_shared(std::size_t&, std::size_t&)’
               size,size);```

**Comment by tbetcke** [comment]
Dear Thomas, this branch is in heavy development and does not always compile yet. All of Armadillo has now been replaced by eigen. I am currently finishing up replacing the Trilinos sparse matrices by Eigen sparse matrices so that we will be able to remove the Trilinos dependency. This is almost complete now (still fixing minor issues). Once it is tested it will be merged into development and then hopefully next week sometime into master as 2.9.1 version together with other fixes.

**Comment by thisch** [comment]
Hello Timo, 

sry if this was already known to you. Thx for your great work on cleaning up the code base and replacing Trilinos stuff by eigen!!

Best regards,
Thomas
