### ISSUE TITLE
Solver gmres stops because of slow convergence and too small default maxRestart =20

### ISSUE THREAD

**Issue by aleks54** [bempp/bempp#208]
I am useing 2-years old 1.1 version of bem++. For one of my tasks it appeared that the maximal restarts parameter in the solver parameters list must be increased. I am not a C++ professional and cannot find a way to  achieve this. I have only found how to increase the maximal interations parameter, but it is not enough as the maximal Restarts is reached. Alternatively (if this is difficult or impossible) can i restart the whole solver with the already achieved approximate solution as a starting point to have another default 20 restarts available?

**Comment by wsmigaj** [comment]
Hello,

are you using the Python or the C++ interface?

Best regards,
Wojciech

**Comment by aleks54** [comment]
I use c++.
I even tried to edit the default value in trilinos and to recompile
the library, but something went wrong.
Glad to know that you are still working with bem++.
You have helped me a lot 2 years ago.
Aleks.

**Comment by wsmigaj** [comment]
Hi Aleks,

thanks for your kind words :-). I don't really work on BEM++ much any more, but I still receive GitHub notifications.

I'll have a look at your issue in the evening.

Best regards,
Wojciech

**Comment by wsmigaj** [comment]
Hi Aleks,

the linear solver's options are set via the ``ParameterList`` object passed to the ``DefaultIterativeSolver::initializeSolver()`` function.

BEM++ provides a convenience function ``defaultGmresParameterList()`` that creates such a parameter list instructing the ``DefaultIterativeSolver`` to use a GMRES solver with a prescribed tolerance and maximum number of iterations. If you want to edit the value of other options, you can construct a ``ParameterList`` object manually and pass it to ``initializeSolver()``. You can use the body of ``defaultGmresParameterList()`` as a template.

For example, to set the maximum number of restarts to 100, you can use the following code:
```   
    Teuchos::RCP<Teuchos::ParameterList> paramList(
                new Teuchos::ParameterList("DefaultParameters"));
    paramList->set("Solver Type", "Pseudo Block GMRES");
    Teuchos::ParameterList& solverTypesList = paramList->sublist("Solver Types");
    Teuchos::ParameterList& pseudoBlockGmresList =
             solverTypesList.sublist("Pseudo Block GMRES");
    pseudoBlockGmresList.set("Convergence Tolerance", 1e-8);
    pseudoBlockGmresList.set("Maximum Iterations", 500);
    pseudoBlockGmresList.set("Maximum Restarts", 100);

    solver.initializeSolver(paramList);
```
(I assumed ``solver`` is an instance of ``DefaultIterativeSolver``.)

When debugging linear solver problems, it is useful to be able to monitor the convergence in real time. If you add the following lines just before the call to ``initializeSolver()`` above, the solver will print out (to standard output) the solution's residual after each iteration:
```
    pseudoBlockGmresList.set("Verbosity",
                             Belos::Errors | Belos::Warnings |
                             Belos::StatusTestDetails);
    pseudoBlockGmresList.set("Output Frequency", 1);
    Teuchos::ParameterList& verboseObjectList =
             paramList->sublist("VerboseObject");
    verboseObjectList.set("Verbosity Level", "medium");
```
To have access to the ``Belos::Errors`` etc. flags, you will need to ``#include`` the ``BelosTypes.hpp`` file.

Hope this helps, best regards,
Wojciech

**Comment by tbetcke** [comment]
Dear Aleks,

alternatively, if you upgrade to the new 2.9 BEM++ version the Python Scipy iterative solver is used by default, which gives you a lot more control. The only disadvantage is that the new H-Matrix module is not yet finished (it will be for the final version 3.0).  Also, may I ask you to pose non-bug questions on the mailing list at:

https://groups.google.com/forum/#!forum/bempp

Timo

**Comment by aleks54** [comment]
Thank you Wojciech.
It works.
Aleks
