### ISSUE TITLE
Compilation Issue with FEniCS on Mac

### ISSUE THREAD

**Issue by nicolassalles** [bempp/bempp#210]
On Mac OS X 10.10.2 with anaconda and MKL, I tried to install the development branch with FEniCS but I get the following error:

CMake Error at /Users/nsalles/bempp_dev/build/external/src/DOLFIN-stamp/DOLFIN-build.cmake:16 (message):
  Command failed: 2
   '/Applications/Xcode.app/Contents/Developer/usr/bin/make'
  See also
    /Users/nsalles/bempp_dev/build/external/src/DOLFIN-stamp/DOLFIN-build-*.log
make[2]: *** [external/src/DOLFIN-stamp/DOLFIN-build] Error 1
make[1]: *** [CMakeFiles/DOLFIN.dir/all] Error 2

The content of the DOLFIN-build-out is only:
Linking CXX shared library libdolfin.dylib

The content of DOLFIN-build-err.log is available here: http://pastebin.com/EusHL3xQ

The installation works fine without FEniCS.

**Comment by tbetcke** [comment]
In the development branch support for building FEniCS and the BEM++ dependencies by Homebrew has been activated. This solves the above issues.
