### ISSUE TITLE
Build issue with dune-bempp

### ISSUE THREAD

**Issue by mscroggs** [bempp/bempp#211]
When running make, it fails with the message: 
"A directory with the name dune-bempp already exists.
Do you want to continue anyway?"

after deleting the directory build/src/external/dune-bempp, make runs ok

**Comment by mscroggs** [comment]
Sorry, I meant build/external/src/dune-bempp

**Comment by tbetcke** [comment]
Two questions.

- Does the error appear with the master or development branch?
- Does it appear upon a clean install?

Timo

**Comment by mscroggs** [comment]
It's in the development branch.
My current install is fine. The problem occurred when trying to do a clean install without anaconda.

**Comment by tbetcke** [comment]
Thanks. Could not yet test the new merges in the development branch under Ubuntu. Will need to check it.

Timo

**Comment by tbetcke** [comment]
Fixed Ubuntu 14.04 build issues.
