### ISSUE TITLE
download boost_1_49.tar.gz failed

### ISSUE THREAD

**Issue by SvenFanghaenel** [bempp/bempp#215]
Hello
I tried to install BEM++ 2.0 with EPD.
The installation is failed because the the boost_url does not exist.
If i try to download boost direct from boost and compile i run in a lot of trouble because the 
boost_url (in boost.py) in now a other one.
Do you know how to fix this problem
Thanx Sven

**Comment by wsmigaj** [comment]
Hi Sven,

the ``http://www.bempp.org/files/boost_1_49.tar.gz`` file seems to have been inadvertently deleted from the server during the recent reorganisation of the BEM++ webpage. Timo or Matthew, could you put it back there, please?

In the meantime, I've put a copy of this file at https://www.dropbox.com/s/fhlx2zsxnw44tsy/boost_1_49.tar.gz?dl=0. Sven, you can download it from there, put it in the ``installer/files`` subdirectory of the BEM++ source directory and rerun the installer (``python bempp_setup.py -b bempp_setup.cfg``). The installer should detect that the file is on the disk and not try to download it again.

Best regards,
Wojciech

**Comment by SvenFanghaenel** [comment]
Hi Wojciech
unfortunately there is no subdirectory files in the BEM source
Thanx Sven

Am 11.06.2015 um 11:55 schrieb Wojciech Śmigaj:

**Comment by wsmigaj** [comment]
The subdirectory is **installer**/files.

Wojciech

**Comment by SvenFanghaenel** [comment]
sorry i have founded. It appears after the first installation try.
Sorry


Am 11.06.2015 um 14:04 schrieb Wojciech Śmigaj:

**Comment by wsmigaj** [comment]
I'm glad the workaround allowed you to install BEM++! Meanwhile I'm reopening this issue, because it can only be considered fixed once someone puts the tarball back on the server.

Wojciech

**Comment by tbetcke** [comment]
Dear Sven,

why do you still want to use the old version? The current development
version is quite advanced and preferable.
In the development branch we even have our own working H-Matrix
implementation. If you need any support for a specific problem let me know
and we can help you adapt the new version to your problem.

Best wishes

Timo

On 11 June 2015 at 16:52, Wojciech Śmigaj <notifications@github.com> wrote:

> Reopened #215 <https://github.com/bempp/bempp/issues/215>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/215#event-328643842>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by SvenFanghaenel** [comment]
Hi Timo

I used the old version because all scripts that i use for my 
calculations are written for the old Ahmed H-Matrix implementation.

Greatings Sven from cologne

Am 11.06.2015 um 21:33 schrieb tbetcke:

**Comment by thisch** [comment]
I have a lot of unit tests written for bempp2.0, which I still want to run in order to compare them with the devel version of bempp.

**Comment by tbetcke** [comment]
Hi,

we are currently out of space on our website. I have requested a quota increase. Once I have this I can upload the missing file.

Timo

**Comment by tbetcke** [comment]
The missing file has now been added.
