### ISSUE TITLE
AHMED support for BEM++ 2.0

### ISSUE THREAD

**Issue by elouelk** [bempp/bempp#216]
Hello,

I recently managed to install bem 2.0 without the support for H-Matrix but since I am going to need them very soon, I tried downloading AHMED 1.0 but the link was down. Do you know where I can get that version of AHMED?
I tried installing BEM 2.9.0 with the built in support for H-Matrix, but I had an error with the cython compilation (I believe this issue is still being adressed).

Best regards,
elouelk

**Comment by wsmigaj** [comment]
Hi elouelk,

regarding the status of AHMED 1.0, please have a look at Timo's response to a similar question asked in issue #171.

Best regards,
Wojciech

**Comment by tbetcke** [comment]
Dear Elouelk,

our current development version has some nicely working H-Matrix support now without requiring AHMED. It is not yet officially releases. But if you are interested I can either give you instructions to compile it or send you binary packages for Debian/Ubuntu.

Timo
