### ISSUE TITLE
eigen issue on Ubuntu

### ISSUE THREAD

**Issue by mscroggs** [bempp/bempp#217]
The version of eigen in the Ubuntu repos is older than the one we've used to develop. The following functions are missing from the class Eigen::JacobiSVD

rank
setThreshold

Installing newer eigen from source fixes this but it would be nice if we take these out.

**Comment by mdavezac** [comment]
Which version of Ubuntu is this? We could try and detect the version of eigen and download it if necessary.

**Comment by mscroggs** [comment]
14.10 with eigen 3.2.1-2

**Comment by c-abird** [comment]
I have the same problem with Ubuntu 14.04 and libeigen3-dev 3.2.0-8

**Comment by tbetcke** [comment]
Hi,

these two routines are easy to replace. I should be able to do it this Wednesday (no time to work on code before).
Best wishes

Timo

**Comment by tbetcke** [comment]
This should be fixed now in the development branch. 
Timo

**Comment by c-abird** [comment]
works for me, thank you very much
