### ISSUE TITLE
pseudoinverse in BEM++ 2.9

### ISSUE THREAD

**Issue by c-abird** [bempp/bempp#218]
Is there a way to access the pseudoinverse of an operator in the Python interface of BEM++ 2.9? I would like to be able to cache the pseudoinverse of the identity matrix, e.g.

    invIdOp = pseudoinverse(identity(trace_space, trace_space, bempp_space)).weak_form()

For BEM++ 2.0.3 there was a feature branch python-pseudoinverse, see also #91 .

**Comment by tbetcke** [comment]
Hi,

I have actually just written such a routine. I will load it up later today.

Timo

On Saturday, 18 July 2015, Claas Abert <notifications@github.com> wrote:

> Is there a way to access the pseudoinverse of an operator in the Python
> interface of BEM++ 2.9? I would like to be able to cache the pseudoinverse
> of the identity matrix, e.g.
>
> invIdOp = pseudoinverse(identity(trace_space, trace_space, bempp_space)).weak_form()
>
> For BEM++ 2.0.3 there was a feature branch python-pseudoinverse, see also
> #91 <https://github.com/bempp/bempp/issues/91> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/218>.
>


-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by tbetcke** [comment]
The development branch now has a Python class 'InverseSparseDiscreteBoundaryOperator', which takes a SparseDiscreteBoundaryOperator in the constructor and otherwise behaves like a DiscreteBoundaryOperator.

**Comment by c-abird** [comment]
Hi Timo,

thanks for the quick reply! I'm getting an "IndexError: too many indices" error when performing matrix vector multiplication with the InverseSparseDiscreteBoundaryOperator. I managed to get things working by calling

    res = np.zeros(x.shape[0],dtype='float64')
    res[:] = self._solve_fun(x[:])

instead of

    res = np.zeros((self.shape[0],x.shape[1]),dtype='float64')
    for i in range(x.shape[1]):
      res[:,i] = self._solve_fun(x[:,i])

in discrete_boundary_operator.mako.pyx line 494. However, I think this might not be right thing to do for the general case?

Best regards, Claas

**Comment by tbetcke** [comment]
Thanks. This is fixed now. The case that the input only has one dimension was not handled correctly. Your fix would have failed for matrix right-hand sides. This is due to some oddities in the interface of the SuperLU solver in Scipy.
