### ISSUE TITLE
Set VerbosityLevel in BEM++ 2.9

### ISSUE THREAD

**Issue by c-abird** [bempp/bempp#219]
Is there a way to set the verbosity level in the Python interface of BEM++ 2.9?

**Comment by tbetcke** [comment]
Currently not as there are plans to implement a proper Python accessible logging system.

**Comment by thisch** [comment]
Please take a look at the python/c++ logger interface used in the espressopp project (https://github.com/espressopp/espressopp). For a minimal standalone example see https://github.com/thisch/boost_python_logger.

**Comment by tbetcke** [comment]
Dear Thomas,

thanks a lot. This is the kind of solution I am planning.

Timo

On 27 July 2015 at 20:48, Thomas Hisch <notifications@github.com> wrote:

> Please take a look at the python/c++ logger interface used in the
> espressopp project (https://github.com/espressopp/espressopp). For a
> minimal standalone example see
> https://github.com/thisch/boost_python_logger.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/219#issuecomment-125323982>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519
