### ISSUE TITLE
GmshInterface has no attribute ``grid``

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#223]
I would like to open a gmsh file and convert it into a bempp Grid object. However, due to some changes (I guess in May) the interface used in the ``test_gmsh.py `` unit tests has changed. BTW, the unit tests in ``test_gmsh.py`` are not run by ``bempp.test()`` and fail in the ``development`` branch.

**Comment by tbetcke** [comment]
Thanks for the bug report. I will check the unit test. We changed the infrastructure for importing external files. To simply read a file you can use the function bempp.import_grid. This is a simple interface to the class bempp.file_interfaces.FileReader, which has a lot more options.

**Comment by tbetcke** [comment]
One more comment. Currently, a Gmsh file needs to have the ending ".msh". Otherwise, it is not recognised.

**Comment by thisch** [comment]
Thx Timo.  The ``import_grid`` function is able to import my gmsh file.
