### ISSUE TITLE
Kudos: tenfold speed increase @development branch

### ISSUE THREAD

**Issue by thisch** [bempp/bempp#224]
I'm really surprised that switching to the new development branch has decreased the runtime of computationally expensive BEM parts (assembling gridfunctions and evaluating potentail ops) of my code by a factor 10!! This is impressive! Thank you all for your hard work!

**Comment by thisch** [comment]
Do you have a bempp benchmark suite, in order to keep track of speed improvements and also of regressions (see http://speed.pypy.org/ or https://pv.github.io/scipy-bench/)? If not, take a look at the airspeed velocity project https://github.com/spacetelescope/asv

**Comment by thisch** [comment]
Hmmmm (all-clear), I've just found out that this large speed increase is due to the quadstrategy order used in my bempp2.0 calculations. Its default value is order=7, which is way too high. As I don't have set/customized the quadstrategy order in bempp3 (I guess the default order is 1), the number of function evaluations of the traces between bempp3 and bempp2 differs by the observed factor 10. I didn't notice this difference in # of function evaluations, as the accuracy checks in my unit tests still passed with quadstrategy order=1 in bempp3. There is one odd thing, though, setting the quadstrategy order to 1 in my bempp2 code leads to test failures (the numerical errors are too large), whereas the tests pass with bempp3. Anyway, my code runs much faster now :)

BTW, how can I set the quadstrat. order in bempp3?

**Comment by thisch** [comment]
@tbetcke, is it possible that setting quadrature orders (``parameters.quadrature.*.double_order``) does not have an effect on the accuracy yet?

**Comment by tbetcke** [comment]
Hi Thomas, it should work. I will check it again.

Timo

**Comment by tbetcke** [comment]
Dear Thomas,

I checked and the double orders work as expected. Do you have an example, where it fails?
Timo

**Comment by thisch** [comment]
Hi Timo,

I will try to come up with an example today. Am I right, that the number of function evaluations to create a gridfunction of the traces depends on the quadrature order? (In my bempp2 build this is the case, however not in the devel branch).

Does it suffice to set the orders with the following code?

```py
myord = 4
parameters = bem.common.global_parameters()
parameters.quadrature.near.double_order = myord
parameters.quadrature.medium.double_order = myord
parameters.quadrature.far.double_order = myord
```

**Comment by tbetcke** [comment]
Hi Thomas,

Grid function objects only depend on the single_order parameter. The name
comes from the projection of grid function only involving integrals over
single elements. 'double_order' is for the operator assembly as here we
integrate over pairs of elements.

I am now working more on the documentation as this is the main obstacle
towards a new full release.
Best wishes

Timo

On 10 August 2015 at 09:54, Thomas Hisch <notifications@github.com> wrote:

> Hi Timo,
>
> I will try to come up with an example today. Am I right, that the number
> of function evaluations to create a gridfunction of the traces depends on
> the quadrature order? (In my bempp2 build this is the case, however not in
> the devel branch).
>
> Does it suffice to set the orders with the following code?
>
> myord = 4
> parameters = bem.common.global_parameters()
> parameters.quadrature.near.double_order = myord
> parameters.quadrature.medium.double_order = myord
> parameters.quadrature.far.double_order = myord
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/224#issuecomment-129371251>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by thisch** [comment]
Hi Timo,

I see. Documentation and more examples/unit tests would be great. Looking forward to that. 

Even if I change the single order parameter I still don't see a change in the number of function evalutations.

Here is a (updated) minmal example:
```py
def main(meshfile=None):
    import bempp as bem

    print("loading mesh '%s' .." % meshfile)
    grid = bem.import_grid("/home/thomas/bempp/examples/meshes/%s.msh" % meshfile)
    print(".. done")

    pconsts = bem.function_space(grid, "DP", 0)
    plins = bem.function_space(grid, "P", 1)
    ctr = [0]

    def eval_dirichlet_data(point, n, domain_index, result):
        ctr[0] += 1

    for quadorder in [4, 6]:
        print("QO %d" % quadorder)
        parameters = bem.common.global_parameters()
        parameters.quadrature.near.double_order = quadorder
        parameters.quadrature.medium.double_order = quadorder
        parameters.quadrature.far.double_order = quadorder

        parameters.quadrature.near.single_order = quadorder
        parameters.quadrature.medium.single_order = quadorder
        parameters.quadrature.far.single_order = quadorder

        print("creating GF ..")
        ctr[0] = 0
        bem.GridFunction(
            plins, dual_space=pconsts,
            fun=eval_dirichlet_data, complex_data=True)
        print("CTR %d" % ctr[0])
        print(".. done")

if __name__ == '__main__':
    meshfile = 'sphere-h-0.1'
    # meshfile = 'sphere-h-0.05'

    main(meshfile=meshfile)

```

**Comment by tbetcke** [comment]
Hi Thomas,

there are two ways to change parameters for an operator or a Gridfunction.

1.)  There is a global singleton object named 'bempp.global_parameters'.
This is an already instantiated object.
2.) Create your own global_parameters object (as you have done), and pass
it over to the GridFunction using the keyword argument parameters (see help
text of GridFunction).

The relevant parameter in the parameters object is
'quadrature.far.single_order'. The reason is that there are two types of
situations, where the singleOrder is relevant, for GridFunctions and for
evaluation of potentials off surface. For the potential evaluation the
distance of the singularity is important. For the GridFunction there is no
singularity, hence we use the far field rule.

So in order to globally change the quadrature order for GridFunctions just
use

bempp.global_parameters.quadrature.far.single_order = my_new_order

By the way, there was still indeed a bug in the parameter handling of
GridFunctions. It did not read the global singleton correctly. I have
pushed a fix to the development branch.

Timo

On 10 August 2015 at 10:26, Thomas Hisch <notifications@github.com> wrote:

> Hi Timo,
>
> I see. Documentation and more examples/unit tests would be great. Looking
> forward to that.
>
> Even if I change the single order parameter I still don't see a change in
> the number of function evalutations.
>
> Here is a (updated) minmal example:
>
> def main(meshfile=None):
>     import bempp as bem
>
>     print("loading mesh '%s' .." % meshfile)
>     grid = bem.import_grid("/home/thomas/bempp/examples/meshes/%s.msh" % meshfile)
>     print(".. done")
>
>     pconsts = bem.function_space(grid, "DP", 0)
>     plins = bem.function_space(grid, "P", 1)
>     ctr = [0]
>
>     def eval_dirichlet_data(point, n, domain_index, result):
>         ctr[0] += 1
>
>     for quadorder in [4, 6]:
>         print("QO %d" % quadorder)
>         parameters = bem.common.global_parameters()
>         parameters.quadrature.near.double_order = quadorder
>         parameters.quadrature.medium.double_order = quadorder
>         parameters.quadrature.far.double_order = quadorder
>
>         parameters.quadrature.near.single_order = quadorder
>         parameters.quadrature.medium.single_order = quadorder
>         parameters.quadrature.far.single_order = quadorder
>
>         print("creating GF ..")
>         ctr[0] = 0
>         bem.GridFunction(
>             plins, dual_space=pconsts,
>             fun=eval_dirichlet_data, complex_data=True)
>         print("CTR %d" % ctr[0])
>         print(".. done")
> if __name__ == '__main__':
>     meshfile = 'sphere-h-0.1'
>     # meshfile = 'sphere-h-0.05'
>
>     main(meshfile=meshfile)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/224#issuecomment-129378105>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519
