### ISSUE TITLE
Setting Up BEM++ tests suite on new Legion OS

### ISSUE THREAD

**Issue by jenshnielsen** [bempp/bempp#226]
Some Progress have been made. Fixed issue with CMake and curl without https support

At this stage the Intel build fails with a Cython related error 

The Gnu build works but requires a manual setting of the Lapack and Blas libraries. Armadillo 
also fails to pickup these libraries and tests that requires Armadillo with Lapack/Atlas fails

To shorten the build time we should pre build the dependencies as modules:

- [ ] TBB
- [ ] Dune
- [x] Boost (Picks up the one on Legion already)
- [ ] Eigen3 (Already on Legion but not picked up)
- [ ] Patchelf
- [ ] Doxygen (Docs only)

**Comment by jenshnielsen** [comment]
Adding 

`export LDFLAGS="-lirc $LDFLAGS" ` seems to fix the Cython issue with Intel. Now that also fails due to Armadillo build without Lapack support.

**Comment by jenshnielsen** [comment]
Armadillo needs to be build with something like (For GNU)

```
cmake .. -DATLAS_CBLAS_INCLUDE_DIR=/shared/ucl/apps/atlas/3.10.2/gnu-4.9.2/include -DATLAS_CLAPACK_INCLUDE_DIR=/shared/ucl/apps/atlas/3.10.2/gnu-4.9.2/include -Dsatlas_LIBRARY=/shared/ucl/apps/atlas/3.10.2/gnu-4.9.2/lib/libsatlas.so -DLAPACK_LIBRARY=/shared/ucl/apps/atlas/3.10.2/gnu-4.9.2/lib/libsatlas.so
```

to correctly build against ATLAS and ATLAS's bundled LAPACK. It correctly picks up MKL for Intel automatically but that it not enough apparently it need ATLAS

**Comment by tbetcke** [comment]
Dear Jens,

please be aware that the 'master' branch is heavily outdated in terms of
dependencies. In the development branch we are not using Trilinos or
Armadillo any more. Instead everything uses Eigen and there are no direct
BLAS dependencies. Let me know if you want to talk this through. This has
simplified building BEM++ significantly compared to master.

Best wishes

Timo

On 11 August 2015 at 13:31, Jens Hedegaard Nielsen <notifications@github.com
> wrote:

> Armadillo needs to be build with something like (For GNU)
>
> cmake .. -DATLAS_CBLAS_INCLUDE_DIR=/shared/ucl/apps/atlas/3.10.2/gnu-4.9.2/include -DATLAS_CLAPACK_INCLUDE_DIR=/shared/ucl/apps/atlas/3.10.2/gnu-4.9.2/include -Dsatlas_LIBRARY=/shared/ucl/apps/atlas/3.10.2/gnu-4.9.2/lib/libsatlas.so -DLAPACK_LIBRARY=/shared/ucl/apps/atlas/3.10.2/gnu-4.9.2/lib/libsatlas.so
>
> to correctly build against ATLAS and ATLAS's bundled LAPACK. It correctly
> picks up MKL for Intel automatically but that it not enough apparently it
> need ATLAS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/226#issuecomment-129857335>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by jenshnielsen** [comment]
Thanks, Lets give up testing Master then. That sounds like a waist of time at this stage

**Comment by tbetcke** [comment]
Exactly. The only reason why I haven't yet upgraded master is that the
documentation for the development branch is not yet complete.

Timo

On 11 August 2015 at 13:36, Jens Hedegaard Nielsen <notifications@github.com
> wrote:

> Thanks, Lets give up testing Master then. That sounds like a waist of time
> at this stage
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/226#issuecomment-129858190>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519
