### ISSUE TITLE
strange coredump when using higher order spaces

### ISSUE THREAD

**Issue by florian98765** [bempp/bempp#228]
hello, i am currently trying to implement the higher order mappings that i was using for my standalone code into the new bem++ version. The mapping seems to work (although the default quadrature order needs to be increased to fit the order of the target function space). 

at the moment i am still facing a strange core dump when setting up the boundary operators. This is a small example that creates the error:

```python
import dolfin
from bempp import function_space, GridFunction
from bempp.fenics_interface import coupling
from bempp.operators.boundary.helmholtz import single_layer, double_layer
from bempp.operators.boundary.sparse import identity
from bempp import grid_from_element_data
import numpy as np

# Create meshes
mesh = dolfin.UnitCubeMesh(10, 10, 10)

bm = dolfin.BoundaryMesh(mesh,"exterior",False)
bm_nodes  = bm.entity_map(0).array().astype(np.int64)
bm_coords = bm.coordinates()
bm_cells  = bm.cells()
bempp_grid = grid_from_element_data(bm_coords.transpose(),bm_cells.transpose())

# Define function spaces
#fenics_space = dolfin.FunctionSpace(mesh, "CG", 2)
#trace_space, trace_matrix = coupling.fenics_to_bempp_trace_data(fenics_space)
#bempp_space = function_space(trace_space.grid, "P", 1)

trace_space = function_space(bempp_grid, "P", 2)
bempp_space = function_space(bempp_grid, "P", 1)

# Define operators
id_op = identity(trace_space, trace_space, bempp_space)
mass = identity(bempp_space, trace_space, trace_space)
dlp = double_layer(trace_space, trace_space, bempp_space, 10.)
slp = single_layer(bempp_space, trace_space, bempp_space, 10.)

id_op - dlp # THIS CREATES A STRANGE CORE DUMP
```

I get the following output:
```
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
[florian-PC02:22372] *** Process received signal ***
[florian-PC02:22372] Signal: Aborted (6)
[florian-PC02:22372] Signal code:  (-6)
[florian-PC02:22372] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0xfc90) [0x7ffe0c6e1c90]
[florian-PC02:22372] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7ffe0c344e37]
[florian-PC02:22372] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7ffe0c346528]
[florian-PC02:22372] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x16d) [0x7ffdfcb4a05d]
[florian-PC02:22372] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5eed6) [0x7ffdfcb47ed6]
[florian-PC02:22372] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5ef21) [0x7ffdfcb47f21]
[florian-PC02:22372] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5f139) [0x7ffdfcb48139]
[florian-PC02:22372] [ 7] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5ddd2) [0x7ffdfcb46dd2]
[florian-PC02:22372] [ 8] /home/florian/git/bempp2.9/build/lib/libbempp.so(_ZNK5Bempp40PiecewisePolynomialContinuousScalarSpaceIdE17spaceIsCompatibleERKNS_5SpaceIdEE+0x1e2) [0x7ffdd3471362]
[florian-PC02:22372] [ 9] /home/florian/git/bempp2.9/build/python_package/bempp/space/space.so(_ZN5boost6detail7variant15visitation_implIN4mpl_4int_ILi0EEENS1_20visitation_impl_stepINS_3mpl6l_iterINS7_6l_itemINS3_5long_ILl8EEENS_10shared_ptrIN5Bempp5SpaceISt7complexIfEEEEENS9_INSA_ILl7EEENSC_IKSH_EENS9_INSA_ILl6EEENSC_INSE_ISF_IdEEEEENS9_INSA_ILl5EEENSC_IKSO_EENS9_INSA_ILl4EEENSC_INSE_IfEEEENS9_INSA_ILl3EEENSC_IKSU_EENS9_INSA_ILl2EEENSC_INSE_IdEEEENS9_INSA_ILl1EEENSC_IKS10_EENS7_5l_endEEEEEEEEEEEEEEEEEEENS8_IS15_EEEENS1_14invoke_visitorINS1_27apply_visitor_binary_unwrapIKNSD_13SpaceVariants12IsCompatibleEKNS_7variantISI_ISL_SP_SS_SV_SY_S11_S14_EEEEEEEPKvNS1N_18has_fallback_type_EEENT1_11result_typeEiiRS1U_T2_NS3_5bool_ILb0EEET3_PT_PT0_+0x8c) [0x7ffdd0a699dc]
[florian-PC02:22372] [10] /home/florian/git/bempp2.9/build/python_package/bempp/space/space.so(+0x12911) [0x7ffdd0a67911]
[florian-PC02:22372] [11] /home/florian/git/bempp2.9/build/python_package/bempp/space/space.so(+0x12c08) [0x7ffdd0a67c08]
[florian-PC02:22372] [12] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0xc671) [0x7ffdd0c7d671]
[florian-PC02:22372] [13] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0x18b83) [0x7ffdd0c89b83]
[florian-PC02:22372] [14] python() [0x4bb04b]
[florian-PC02:22372] [15] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0xc591) [0x7ffdd0c7d591]
[florian-PC02:22372] [16] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0x1d873) [0x7ffdd0c8e873]
[florian-PC02:22372] [17] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0xc591) [0x7ffdd0c7d591]
[florian-PC02:22372] [18] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0xc6e7) [0x7ffdd0c7d6e7]
[florian-PC02:22372] [19] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0x1db29) [0x7ffdd0c8eb29]
[florian-PC02:22372] [20] python(PyNumber_Subtract+0x5f) [0x52181f]
[florian-PC02:22372] [21] python(PyEval_EvalFrameEx+0x3444) [0x4cd9a4]
[florian-PC02:22372] [22] python(PyEval_EvalCodeEx+0x411) [0x4c92a1]
[florian-PC02:22372] [23] python() [0x50391f]
[florian-PC02:22372] [24] python(PyRun_FileExFlags+0x82) [0x4f9392]
[florian-PC02:22372] [25] python(PyRun_SimpleFileExFlags+0x197) [0x4f8497]
[florian-PC02:22372] [26] python(Py_Main+0x55d) [0x49845d]
[florian-PC02:22372] [27] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7ffe0c32fec5]
[florian-PC02:22372] [28] python() [0x497e16]
[florian-PC02:22372] *** End of error message ***
Aborted (core dumped)
```

Do you have any ideas how to resolve this?
thanks Florian

**Comment by tbetcke** [comment]
Hi Florian,

I recently reorganised the space classes to implement Adaptivity. A small
bug crept into the compatibility check that was not caught by the unit
tests. I have fixed this now. Let me know if you have any other issues.

Best wishes

Timo

On 12 August 2015 at 09:41, florian98765 <notifications@github.com> wrote:

> hello, i am currently trying to implement the higher order mappings that i
> was using for my standalone code into the new bem++ version. The mapping
> seems to work (although the default quadrature order needs to be increased
> to fit the order of the target function space).
>
> at the moment i am still facing a strange core dump when setting up the
> boundary operators. This is a small example that creates the error:
>
> import dolfinfrom bempp import function_space, GridFunctionfrom bempp.fenics_interface import couplingfrom bempp.operators.boundary.helmholtz import single_layer, double_layerfrom bempp.operators.boundary.sparse import identityfrom bempp import grid_from_element_dataimport numpy as np
> # Create meshes
> mesh = dolfin.UnitCubeMesh(10, 10, 10)
>
> bm = dolfin.BoundaryMesh(mesh,"exterior",False)
> bm_nodes  = bm.entity_map(0).array().astype(np.int64)
> bm_coords = bm.coordinates()
> bm_cells  = bm.cells()
> bempp_grid = grid_from_element_data(bm_coords.transpose(),bm_cells.transpose())
> # Define function spaces#fenics_space = dolfin.FunctionSpace(mesh, "CG", 2)#trace_space, trace_matrix = coupling.fenics_to_bempp_trace_data(fenics_space)#bempp_space = function_space(trace_space.grid, "P", 1)
>
> trace_space = function_space(bempp_grid, "P", 2)
> bempp_space = function_space(bempp_grid, "P", 1)
> # Define operators
> id_op = identity(trace_space, trace_space, bempp_space)
> mass = identity(bempp_space, trace_space, trace_space)
> dlp = double_layer(trace_space, trace_space, bempp_space, 10.)
> slp = single_layer(bempp_space, trace_space, bempp_space, 10.)
>
> id_op - dlp # THIS CREATES A STRANGE CORE DUMP
>
> I get the following output:
>
> terminate called after throwing an instance of 'std::bad_cast'
>   what():  std::bad_cast
> [florian-PC02:22372] *** Process received signal ***
> [florian-PC02:22372] Signal: Aborted (6)
> [florian-PC02:22372] Signal code:  (-6)
> [florian-PC02:22372] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0xfc90) [0x7ffe0c6e1c90]
> [florian-PC02:22372] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7ffe0c344e37]
> [florian-PC02:22372] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7ffe0c346528]
> [florian-PC02:22372] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x16d) [0x7ffdfcb4a05d]
> [florian-PC02:22372] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5eed6) [0x7ffdfcb47ed6]
> [florian-PC02:22372] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5ef21) [0x7ffdfcb47f21]
> [florian-PC02:22372] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5f139) [0x7ffdfcb48139]
> [florian-PC02:22372] [ 7] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5ddd2) [0x7ffdfcb46dd2]
> [florian-PC02:22372] [ 8] /home/florian/git/bempp2.9/build/lib/libbempp.so(_ZNK5Bempp40PiecewisePolynomialContinuousScalarSpaceIdE17spaceIsCompatibleERKNS_5SpaceIdEE+0x1e2) [0x7ffdd3471362]
> [florian-PC02:22372] [ 9] /home/florian/git/bempp2.9/build/python_package/bempp/space/space.so(_ZN5boost6detail7variant15visitation_implIN4mpl_4int_ILi0EEENS1_20visitation_impl_stepINS_3mpl6l_iterINS7_6l_itemINS3_5long_ILl8EEENS_10shared_ptrIN5Bempp5SpaceISt7complexIfEEEEENS9_INSA_ILl7EEENSC_IKSH_EENS9_INSA_ILl6EEENSC_INSE_ISF_IdEEEEENS9_INSA_ILl5EEENSC_IKSO_EENS9_INSA_ILl4EEENSC_INSE_IfEEEENS9_INSA_ILl3EEENSC_IKSU_EENS9_INSA_ILl2EEENSC_INSE_IdEEEENS9_INSA_ILl1EEENSC_IKS10_EENS7_5l_endEEEEEEEEEEEEEEEEEEENS8_IS15_EEEENS1_14invoke_visitorINS1_27apply_visitor_binary_unwrapIKNSD_13SpaceVariants12IsCompatibleEKNS_7variantISI_ISL_SP_SS_SV_SY_S11_S14_EEEEEEEPKvNS1N_18has_fallback_type_EEENT1_11result_typeEiiRS1U_T2_NS3_5bool_ILb0EEET3_PT_PT0_+0x8c) [0x7ffdd0a699dc]
> [florian-PC02:22372] [10] /home/florian/git/bempp2.9/build/python_package/bempp/space/space.so(+0x12911) [0x7ffdd0a67911]
> [florian-PC02:22372] [11] /home/florian/git/bempp2.9/build/python_package/bempp/space/space.so(+0x12c08) [0x7ffdd0a67c08]
> [florian-PC02:22372] [12] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0xc671) [0x7ffdd0c7d671]
> [florian-PC02:22372] [13] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0x18b83) [0x7ffdd0c89b83]
> [florian-PC02:22372] [14] python() [0x4bb04b]
> [florian-PC02:22372] [15] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0xc591) [0x7ffdd0c7d591]
> [florian-PC02:22372] [16] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0x1d873) [0x7ffdd0c8e873]
> [florian-PC02:22372] [17] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0xc591) [0x7ffdd0c7d591]
> [florian-PC02:22372] [18] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0xc6e7) [0x7ffdd0c7d6e7]
> [florian-PC02:22372] [19] /home/florian/git/bempp2.9/build/python_package/bempp/assembly/boundary_operator.so(+0x1db29) [0x7ffdd0c8eb29]
> [florian-PC02:22372] [20] python(PyNumber_Subtract+0x5f) [0x52181f]
> [florian-PC02:22372] [21] python(PyEval_EvalFrameEx+0x3444) [0x4cd9a4]
> [florian-PC02:22372] [22] python(PyEval_EvalCodeEx+0x411) [0x4c92a1]
> [florian-PC02:22372] [23] python() [0x50391f]
> [florian-PC02:22372] [24] python(PyRun_FileExFlags+0x82) [0x4f9392]
> [florian-PC02:22372] [25] python(PyRun_SimpleFileExFlags+0x197) [0x4f8497]
> [florian-PC02:22372] [26] python(Py_Main+0x55d) [0x49845d]
> [florian-PC02:22372] [27] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7ffe0c32fec5]
> [florian-PC02:22372] [28] python() [0x497e16]
> [florian-PC02:22372] *** End of error message ***
> Aborted (core dumped)
>
> Do you have any ideas how to resolve this?
> thanks Florian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/228>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by florian98765** [comment]
I just checked out the latest development version and now everything runs fine.

thanks for the fast response
greetings Florian
