### ISSUE TITLE
store hmatrix integral operators to file

### ISSUE THREAD

**Issue by florian98765** [bempp/bempp#230]
hi, 

is it possible to store an hmatrix integral operator to a file and reload it. would be a nice feature, especially for testing where i need to create one and the same operator again an again. 

thanks
Florian

**Comment by wsmigaj** [comment]
Hi Florian,

for BEM++ 2.0 there exists user-contributed code that does that -- see issue #95. I don't know, unfortunately, whether there is anything similar for BEM++ 2.9.

Best regards,
Wojciech

**Comment by tbetcke** [comment]
Dear Florian,

this is in planning. We currently have some discussions with the group of
Steffen Boerm in Kiel about creating a file exchange format for H-Matrices.
For BEM++ 2.9+ I am planning a Python based solution to do this.

Best wishes

Timo

On 2 September 2015 at 09:33, Wojciech Śmigaj <notifications@github.com>
wrote:

> Hi Florian,
>
> for BEM++ 2.0 there exists user-contributed code that does that -- see
> issue #95 <https://github.com/bempp/bempp/issues/95>. I don't know,
> unfortunately, whether there is anything similar for BEM++ 2.9.
>
> Best regards,
> Wojciech
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/230#issuecomment-136976049>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by florian98765** [comment]
hello timo,

are there any news about the h-matrix file import / export feature?

greetings 
Florian
