### ISSUE TITLE
Problems installing development branch on Ubuntu 14.04

### ISSUE THREAD

**Issue by c-abird** [bempp/bempp#232]
Since recently I have problems installing bempp from the development branch. Calling cmake yields the following error

    -- Python module Cython could not be found.: Found unsuitable version "0.20.1post0", but required is at least "0.21" (found /usr/lib/python2.7/dist-packages/Cython)
    -- Will now attempt to install Cython locally
    output: 
    
    error: error: Not a URL, existing file, or requirement spec: '==0.21'
    
    
    CMake Error at build/external/src/GreatCMakeCookOff/scripts/PythonPackageLookup.cmake:101 (message):
      Could not install Cython

This seems to have something to do with recent changes in the GreatCMakeCookOff
 package. I'm on Ubuntu 14.04.

**Comment by tbetcke** [comment]
Hi, I need to test it in a virtual machine. You can get around this for now by installing Cython manually.
Let me know if this still leads to issues.

Timo

**Comment by c-abird** [comment]
Hi Timo, thanks for the answer. I'm currently using a hot fix that checks out an old version (commit 89a5439 which is 3 commits behind HEAD) of GreatCMakeCookOff in order to avoid the problem.

**Comment by mdavezac** [comment]
Indeed there was a bug in the cookoff. It should work now.
@c-abird, thanks for raising this
