### ISSUE TITLE
Ctest no longer runs the python tests

### ISSUE THREAD

**Issue by jenshnielsen** [bempp/bempp#234]
Following the latest refactoring the python code including the separation of Python and Cython code CTest no longer runs the python tests. This means that they do not run on Jenkins

Not sure if it is worth to add it back or we should just add 

```
python -c "import bempp.api; bempp.api.test()" 

``` 

to the test scripts.

**Comment by tbetcke** [comment]
We should add the latter to the test scripts. I am slowly transitioning over C++ unit tests to Python to hopefully eventually have all tests run from Python. Until then the proposed fix is good.
