### ISSUE TITLE
Trouble installing BEM++ 2.0 on cluster

### ISSUE THREAD

**Issue by THeffernon** [bempp/bempp#235]
Hi, I am trying to install BEM++ 2.0 on a cluster (RedHat Enterprise Server 6.3), having previously successfully installed it on a desktop (Ubuntu 12.04 LTS).

The following runs and completes successfully:
python bempp_setup.py -b bempp_setup.cfg
python bempp_setup.py -c bempp_setup.cfg

However, the following fails:
python bempp_setup.py -i all bempp_setup.cfg

It appears to fail during the building of Trilinos, with the following output:
**************************************************************************************
...
[ 97%] Building CXX object packages/PyTrilinos/src/CMakeFiles/pytrilinos.dir/PyTrilinos_Epetra_Util.cpp.o
In file included from /local/software/python/2.7.5/include/python2.7/Python.h:8,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/PyTrilinos_Util.h:33,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/PyTrilinos_Epetra_Util.cpp:50:
/local/software/python/2.7.5/include/python2.7/pyconfig.h:1173:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/x86_64-redhat-linux/bits/os_defines.h:39,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/x86_64-redhat-linux/bits/c++config.h:1687,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/stl_algobase.h:60,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/algorithm:61,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/PyTrilinos_Epetra_Util.cpp:30:
/usr/include/features.h:162:1: warning: this is the location of the previous definition
In file included from /local/software/python/2.7.5/include/python2.7/Python.h:8,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/PyTrilinos_Util.h:33,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/PyTrilinos_Epetra_Util.cpp:50:
/local/software/python/2.7.5/include/python2.7/pyconfig.h:1195:1: warning: "_XOPEN_SOURCE" redefined
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/x86_64-redhat-linux/bits/os_defines.h:39,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/x86_64-redhat-linux/bits/c++config.h:1687,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/stl_algobase.h:60,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/algorithm:61,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/PyTrilinos_Epetra_Util.cpp:30:
/usr/include/features.h:164:1: warning: this is the location of the previous definition
In file included from /local/software/python/2.7.5/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1728,
                 from /local/software/python/2.7.5/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /local/software/python/2.7.5/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:15,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/numpy_include.h:46,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/Epetra_NumPyMultiVector.h:33,
                 from /home/tjh1g12/bempp_install/bempp-2.0/build/contrib/trilinos/packages/PyTrilinos/src/PyTrilinos_Epetra_Util.cpp:54:
/local/software/python/2.7.5/lib/python2.7/site-packages/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
[ 97%] Building CXX object packages/PyTrilinos/src/CMakeFiles/pytrilinos.dir/PyTrilinos_EpetraExt_Util.cpp.o
Linking CXX shared library libpytrilinos.so
/usr/bin/ld: /local/software/python/2.7.5/lib/python2.7/config/libpython2.7.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/local/software/python/2.7.5/lib/python2.7/config/libpython2.7.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: *** [packages/PyTrilinos/src/libpytrilinos.so] Error 1
make[1]: *** [packages/PyTrilinos/src/CMakeFiles/pytrilinos.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library libstratimikosbelos.so
[ 97%] Built target stratimikosbelos
make: *** [all] Error 2
============================================================================== 
BEM++ INSTALLATION FAILED WITH ERROR MESSAGE: 
Command 'make -j3' returned non-zero exit status 2
------------------------------------------------------------------------------
Note: A stack trace of the BEM++ installer, providing detailed information
on where the problem occured, has been written to the file 'bempp_setup.err'.
Please include this file if you report the problem to BEM++ developers.
**************************************************************************************

The .err file gives:
**************************************************************************************
Traceback (most recent call last):
  File "bempp_setup.py", line 310, in <module>
    installDependencies(root,config)
  File "bempp_setup.py", line 112, in installDependencies
    libraries[dep].build(root,config)
  File "installer/py_modules/trilinos.py", line 102, in build
    subprocess.check_call("make -j"+str(njobs),shell=True)
  File "/local/software/python/2.7.5/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'make -j3' returned non-zero exit status 2
**************************************************************************************

The configuration file I'm using is shown below:
**************************************************************************************
[Main]

architecture=intel64

prefix=~

build_jobs=3

[Bempp]

build=yes

[MKL]

enable_mkl=yes

source=like_numpy

[BLAS]

[LAPACK]

[AHMED]

enable_ahmed=yes

file_name=/home/tjh1g12/bempp_install/AHMED-1.0.tar.gz

[Boost]

[Dune]

[Swig]

[Trilinos]

[MPI]

[Python]
**************************************************************************************

Could you give me any advice on how to get around this please?

Thanks in advance,
Tim

**Comment by wsmigaj** [comment]
Hi Tim,

one solution would be to install a shared-library version of system Python (you seem to have only a static build installed) or to use a third-party Python, for example Enthought Canopy. 

If you can't or don't want to do that, then you can try appending ``-fPIC`` to the compiler options (as the error message suggests) by adding the lines
```
cflags=-fPIC
cxxflags=-fPIC
```
to the ``[Main]`` section of ``bempp_setup.cfg`` and re-running the BEM++ setup script.

Best regards,
Wojciech

**Comment by tbetcke** [comment]
Dear Tim,

is there a reason why you want to install BEM++ 2.0 ? BEM++ 3.0 is almost ready and I would be happy to provide support to install the current development version.

**Comment by THeffernon** [comment]
Hi Wojciech and Timo,

Wojciech, thanks for the advice. I figured it was something to do with the Python install, but wasn't sure where to add the -fPIC flag. I tried re-running the BEM++ scrip with those flags added to the .cfg, but it still failed at the same point. If I proceed with the installation of version 2.0 I'll see if I can install Anaconda Python on the cluster too, which is what I use locally.

Timo, I'm looking at running a simulation with a large number of boundary elements. I appear to be limited to around 100,000 on my desktop, I was hoping to use a lot more by running the code on our cluster, which has some high memory nodes. I was under the impression that H-matrix support in 2.9.0 was still in development, is this the case?

Thank you both for your help. Kind regards,
Tim

**Comment by tbetcke** [comment]
Hi Tim,

BEM++ 2.0 used AHMED 1.0. There were several license issues with AHMED (it
is very restrictive), and its interfaces frequently change without warning.
It is also not very actively developed any more as far as I have heard.

We started our own H-Matrix library. It is not yet as feature complete as
AHMED, but gives pretty decent performance. This was the biggest holdup to
a new release. But matrix compression is working quite well know and I have
easily scaled it to matrix dimensions of 400k elements for high-frequency
problems on my desktop workstation (granted, it has 200GB RAM). More should
be possible with a bit of parameter optimisation. We are right now working
on getting a model with 700k elements going.

What is still missing is H-Matrix LU and symmetric assembly (i.e.
assembling only half the matrix if the problem is symmetric). These things
are in the works. But right now I am focusing on getting the documentation
finished for the 3.0 release. H-LU is not very crucial. We now have fast
Helmholtz preconditioners (approx. Dirichlet-To-Neumann maps), which for
most domains perform significantly better than H-LU. For Laplace type
problems we also offer opposite order preconditioning on dual spaces.
Calderon preconditioners for Maxwell are currently in the works.

Regarding cluster support. Right now BEM++ only supports assembling
operators on a single cluster node. We have a project going to use IPython
parallel cluster to distribute the assembly on multiple nodes. We are
pretty close to doing it for dense operators, but it will still need a few
more weeks for distributed H-Matrix assembly.

So if you have AHMED 1.0 and don't want to change codes just go ahead and
use BEM++ 2.0 for a little longer. But all the great stuff is currently
happening in the development branch.

Best wishes

Timo




On 25 September 2015 at 10:20, THeffernon <notifications@github.com> wrote:

> Hi Wojciech and Timo,
>
> Wojciech, thanks for the advice. I figured it was something to do with the
> Python install, but wasn't sure where to add the -fPIC flag. I tried
> re-running the BEM++ scrip with those flags added to the .cfg, but it still
> failed at the same point. If I proceed with the installation of version 2.0
> I'll see if I can install Anaconda Python on the cluster too, which is what
> I use locally.
>
> Timo, I'm looking at running a simulation with a large number of boundary
> elements. I appear to be limited to around 100,000 on my desktop, I was
> hoping to use a lot more by running the code on our cluster, which has some
> high memory nodes. I was under the impression that H-matrix support in
> 2.9.0 was still in development, is this the case?
>
> Thank you both for your help. Kind regards,
> Tim
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/235#issuecomment-143168057>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by THeffernon** [comment]
Hi Timo,

That's great news about the development of H-Matrices in 2.9.0. I shall look into the required prerequisites and how to make them available on the cluster, then attempt to compile 2.9.0.

Our cluster has 4 high memory nodes with 32 cores and 256 GB RAM on each. I'm hoping that using one of these nodes would allow the use of my meshes that have around 410K boundary elements.

Kind regards,
Tim

**Comment by tbetcke** [comment]
Dear Tim,

please be aware that the H-Matrix library is not in 2.9.0 but in the
current development branch. So when you check out the source code, say 'git
checkout development' to switch to the current version.

Best wishes

Timo

On 25 September 2015 at 12:15, THeffernon <notifications@github.com> wrote:

> Hi Timo,
>
> That's great news about the development of H-Matrices in 2.9.0. I shall
> look into the required prerequisites and how to make them available on the
> cluster, then attempt to compile 2.9.0.
>
> Our cluster has 4 high memory nodes with 32 cores and 256 GB RAM on each.
> I'm hoping that using one of these nodes would allow the use of my meshes
> that have around 410K boundary elements.
>
> Kind regards,
> Tim
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/235#issuecomment-143189431>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by THeffernon** [comment]
Hi Timo,

Thanks for that, I hadn't realised it was a development branch. I'll make sure I switch to the current development version.

Kind regards,
Tim
