### ISSUE TITLE
Localpython broken

### ISSUE THREAD

**Issue by jenshnielsen** [bempp/bempp#236]
The localpython.sh script and the bempp and ibempp python aliases are broken following the latest refactoring since they don't correctly insert the path to the pure python files in the PYTHONPATH

**Comment by tbetcke** [comment]
Thanks for pointing this out. I am planning to delete these scripts as they were mainly needed when we still needed a bunch of environment variables. Apart from PYTHONPATH if run from the build directory this has become obsolete.
