### ISSUE TITLE
Library not loaded: libiomp5.dylib

### ISSUE THREAD

**Issue by chadesbois** [bempp/bempp#237]
I was able to compile the code. 
When I run the command 
`from bempp import grid_from_sphere` from the python console
I get the following error
`ImportError: dlopen(bempp/grid/grid.so, 2): Library not loaded: libiomp5.dylib`
I'm a bit stuck and am not sure where to look next...

Thanks for you help!

**Comment by wsmigaj** [comment]
Hi,

which version of MacOS, which Python distribution and which implementation of BLAS and LAPACK are you using?

Best regards,
Wojciech

**Comment by wsmigaj** [comment]
And, by the way, which version of BEM++ are you trying to install -- 2.0, 2.9 or the development version from the ``development`` branch?

**Comment by chadesbois** [comment]
Hi, Im on MacOS 10.10.1, working with Python 2.7.10 on Spyder 2.3.1 launched from Anaconda.
I am trying to install the 2.9 version of BEM++  found on the bempp.org website
I am quite new to this so I hope I answered the questions you asked properly and that I am on the right path...

**Comment by wsmigaj** [comment]
Hi,

thanks a lot for this information -- that's exactly what I was after. I'm not too familiar with the installer of BEM++ 2.9 -- perhaps Timo will be able to help you more -- but one thing I can suggest is to try adding the directory in which ``libiomp5.dylib`` is located to the environmental variable ``DYLD_LIBRARY_PATH`` by running the command
```
export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:<directory_containing_libiomp5>
```
prior to starting Python and importing the ``bempp`` module. The directory in question is likely to be the ``lib`` subdirectory of the directory where you installed Anaconda (please check).

Best regards,
Wojciech

**Comment by chadesbois** [comment]
I did what you said, I think I have made some progress, but now I have new error. 
  File "bempp/utils/parameter_list.pxd", line 39, in init bempp.grid.grid (/Users/charlottegegout/bemp2/build/python/bempp/grid/cython_.Users.charlottegegout.bemp2.build.python_package.bempp.include.bempp.grid.grid.cc:18962)
ImportError: No module named parameter_list.

Again, thanks for your help!

**Comment by wsmigaj** [comment]
Hi,

I'm glad you've been able to solve the issue with ``libiomp5.dylib``. I'm not sure I'll be able to help you with the new problem -- I don't know BEM++ 2.9 well enough. 

But come to think of it, you said you were running a Python shell in Spyder. Have you tried to start a Python or IPython shell in a Terminal window using the ``build/bin/bempp`` or ``build/bin/ibempp`` script, as described in the [installation notes](http://www.bempp.org/installation.html#running-bem)? Does it work?

Best regards,
Wojciech
