### ISSUE TITLE
build of bempp fails

### ISSUE THREAD

**Issue by pescap** [bempp/bempp#243]
Hi,
I'm trying to build bempp 2.9 on my mac yosemite 10.10.5 and it fails at 98% with the following error:

/Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6305:23: error:
      assigning to 'const arma::Col<__pyx_t_5bempp_5utils_complex_float> *' from incompatible type '__Pyx_FakeReference<const
      arma::Col<__pyx_t_5bempp_5utils_complex_float> > *'
  __pyx_v_arma_coeffs = (&__pyx_t_1);
                      ^ ~~~~~~~~~~~~
/Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6372:23: error:
      assigning to 'const arma::Col<__pyx_t_5bempp_5utils_complex_double> *' from incompatible type '__Pyx_FakeReference<const
      arma::Col<__pyx_t_5bempp_5utils_complex_double> > *'
  __pyx_v_arma_coeffs = (&__pyx_t_1);
                      ^ ~~~~~~~~~~~~
/Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6439:23: error:
      assigning to 'const arma::Col<__pyx_t_5bempp_5utils_complex_float> *' from incompatible type '__Pyx_FakeReference<const
      arma::Col<__pyx_t_5bempp_5utils_complex_float> > *'
  __pyx_v_arma_coeffs = (&__pyx_t_1);
                      ^ ~~~~~~~~~~~~
/Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6506:23: error:
      assigning to 'const arma::Col<float> *' from incompatible type '__Pyx_FakeReference<const arma::Col<float> > *'
  __pyx_v_arma_coeffs = (&__pyx_t_1);
                      ^ ~~~~~~~~~~~~
/Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6573:23: error:
      assigning to 'const arma::Col<__pyx_t_5bempp_5utils_complex_double> *' from incompatible type '__Pyx_FakeReference<const
      arma::Col<__pyx_t_5bempp_5utils_complex_double> > *'
  __pyx_v_arma_coeffs = (&__pyx_t_1);
                      ^ ~~~~~~~~~~~~
/Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6640:23: error:
      assigning to 'const arma::Col<double> *' from incompatible type '__Pyx_FakeReference<const arma::Col<double> > *'
  __pyx_v_arma_coeffs = (&__pyx_t_1);

I didn't find any reference about this type of problems...

I use:
python 2.7.10
numpy 1.9.3
cython 0.23.3

Any idea?
Thanks!!

**Comment by tbetcke** [comment]
Hi,

This looks like a Cython issue. We tested 2.9 with Cython 0.21. Currently,
I am using 0.22 for the development branch. I will need to test it with the
0.23 version.

Timo

On Wednesday, 30 September 2015, pescap <notifications@github.com> wrote:

> Hi,
> I'm trying to build bempp 2.9 on my mac yosemite 10.10.5 and it fails at
> 93% with the following error:
>
>
> /Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6305:23:
> error:
> assigning to 'const arma::Col<__pyx_t_5bempp_5utils_complex_float> *' from
> incompatible type '__Pyx_FakeReference
> arma::Col<__pyx_t_5bempp_5utils_complex_float> > *'
> __pyx_v_arma_coeffs = (&__pyx_t_1);
> ^ ~~~~~~~~~~~~
>
> /Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6372:23:
> error:
> assigning to 'const arma::Col<__pyx_t_5bempp_5utils_complex_double> *'
> from incompatible type '__Pyx_FakeReference
> arma::Col<__pyx_t_5bempp_5utils_complex_double> > *'
> __pyx_v_arma_coeffs = (&__pyx_t_1);
> ^ ~~~~~~~~~~~~
>
> /Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6439:23:
> error:
> assigning to 'const arma::Col<__pyx_t_5bempp_5utils_complex_float> *' from
> incompatible type '__Pyx_FakeReference
> arma::Col<__pyx_t_5bempp_5utils_complex_float> > *'
> __pyx_v_arma_coeffs = (&__pyx_t_1);
> ^ ~~~~~~~~~~~~
>
> /Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6506:23:
> error:
> assigning to 'const arma::Col *' from incompatible type
> '__Pyx_FakeReference > *'
> __pyx_v_arma_coeffs = (&__pyx_t_1);
> ^ ~~~~~~~~~~~~
>
> /Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6573:23:
> error:
> assigning to 'const arma::Col<__pyx_t_5bempp_5utils_complex_double> *'
> from incompatible type '__Pyx_FakeReference
> arma::Col<__pyx_t_5bempp_5utils_complex_double> > *'
> __pyx_v_arma_coeffs = (&__pyx_t_1);
> ^ ~~~~~~~~~~~~
>
> /Users/paul/virtual/bempp/build/python/bempp/assembly/cython_.Users.paul.virtual.bempp.build.python_package.bempp.include.bempp.assembly.grid_function.cc:6640:23:
> error:
> assigning to 'const arma::Col *' from incompatible type
> '__Pyx_FakeReference > *'
> __pyx_v_arma_coeffs = (&__pyx_t_1);
>
> I didn't find any reference about this type of problems...
>
> I use:
> python 2.7.10
> numpy 1.9.3
> cython 0.23.3
>
> Any idea?
> Thanks!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/243>.
>


-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by pescap** [comment]
Hi,
I tested it with Cython 0.21 and 0.22 and got the same error.

**Comment by jenshnielsen** [comment]
@tbetcke I have successfully build the current development branch with Cython 0.23 which is also what Jenkins currently uses

**Comment by jenshnielsen** [comment]
@pescap As far as I know Pyx_FakeReference was not introduced until Cython 0.22 so I find it surprising that you get that error with Cython 0.21 See https://github.com/cython/cython/commit/40cb5671fea5c2b0eae0d9b81af8e3e022240688

Can you make sure that you start from a clean build directory after downgrading Cython?

**Comment by tbetcke** [comment]
@pescap You may want to try the development branch anyway. It is mostly ready to go and we are busy with documentation. You can already find some chunks of documentation in IPython Notebook format under the `tutorials` subdirectory of the source tree.

**Comment by pescap** [comment]
Hi, I tried with the development branch and the make+build worked successfully! Thanks for your help.
