### ISSUE TITLE
Bempp requires Scipy 0.16 (latest release) and fails with hard to debug error with earlier versions

### ISSUE THREAD

**Issue by jenshnielsen** [bempp/bempp#246]
Even 0.15.1 fails with errors such as 

```
../python/bempp/api/operators/boundary/test/test_modified_helmholtz.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../python/bempp/api/assembly/boundary_operator.py:61: in weak_form
    self._weak_form = self._weak_form_impl()
../python/bempp/api/assembly/boundary_operator.py:312: in _weak_form_impl
    return self._op1.weak_form() + self._op2.weak_form()
../python/bempp/api/assembly/boundary_operator.py:61: in weak_form
    self._weak_form = self._weak_form_impl()
../python/bempp/api/assembly/boundary_operator.py:422: in _weak_form_impl
    self.domain.global_dof_count)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'ZeroDiscreteBoundaryOperator' object has no attribute 'shape'") raised in repr()] SafeRepr object at 0x108aaf8c0>
rows = 66L, columns = 66L

    def __init__(self, rows, columns):
    
        super(ZeroDiscreteBoundaryOperator, self).__init__(dtype=_np.dtype('float64'),
>                                                          shape=(rows, columns))
E       TypeError: __init__() takes at least 3 arguments (3 given)
```

Since support for extending scipy.sparse.linalg.interface.LinearOperator etc. by subclassing was added in 0.16 

This is mainly an issue because the error is so in transparent and Ubuntu etc will be packaging older versions.

**Comment by tbetcke** [comment]
Hi, I am aware of this issue. Originally, I tried to circumvent this by copying the corresponding classes from Scipy 0.16 into the BEM++ Python files (this was a couple of weeks ago). A few days ago I realised that some Scipy functions (in particular the sparse solvers) for certain options used checks whether the operator given was of type LinearOperator. These checks failed now. So I reverted back to relying on Scipy being current. It is not a major problem as the new Ubuntu will have 0.16 and on older versions one can use pip to easily upgrade Scipy. But I agree that it is not perfect. Any other suggestions?

**Comment by jenshnielsen** [comment]
I think we should just add a version check so that we can raise a more informative error.

The error above is better on python 3 than 2 but it's still confusing

**Comment by jenshnielsen** [comment]
I discovered this because one of the mac slaves had 0.15.1 installed and failed with the above error

**Comment by tbetcke** [comment]
Agree with the better error message. Will do it tonight.
