### ISSUE TITLE
Problem running Helemholtz_fem_bem

### ISSUE THREAD

**Issue by alineu** [bempp/bempp#252]
Hi,
I tried to run coupled FEM/BEM example on my laptop but I get this error:

RuntimeError                              Traceback (most recent call last)
<ipython-input-87-03bd2ca4ac1e> in <module>()
----> 1 blocked[0,0] = A.weak_form()-k**2*A2.weak_form()

/home/ali/repos/bempp/build/python_package/bempp/fenics_interface/fenics_operator.pyc in weak_form(self)
     15 
     16         backend = _dolfin.parameters['linear_algebra_backend']
---> 17         _dolfin.parameters['linear_algebra_backend'] = 'uBLAS'
     18         sparse_mat = _dolfin.assemble(self._fenics_weak_form).sparray()
     19         _dolfin.parameters['linear_algebra_backend'] = backend

/usr/lib/python2.7/dist-packages/dolfin/cpp/common.pyc in __setitem__(self, key, value)
   2351             par._assign_bool(value)
   2352         else:
-> 2353             par._assign(value)
   2354 
   2355     def update(self, other):

RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics@fenicsproject.org
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to assign parameter value.
*** Reason:  Illegal value for parameter "linear_algebra_backend". Allowed values are: [Eigen, PETSc, STL].
*** Where:   This error was encountered inside Parameter.cpp.
*** Process: 0
*** 
*** DOLFIN version: 1.6.0
*** Git changeset:  unknown
*** -------------------------------------------------------------------------

which seems to be related to this line:
blocked[0, 0] = A.weak_form() - k**2*A2.weak_form()
Could you please help me fix this?
Thanks

**Comment by tbetcke** [comment]
Hi,

you are running an older version of the FEniCS Interface with the new
FEniCS 1.6. Could you the current BEM++ 2.9.9 version? You find various
binary packages on our homepage. So compilation is not necessary any more.
The current version tests for the linear algebra backend in FEniCS and uses
the PETsC interface if possible. Please note that I have not yet adapted
the coupled FEM/BEM example. So this is likely not going to work any more.
We plan next week the final 3.0 release and I should have one by then.

Best wishes

Timo

On 4 November 2015 at 19:32, alineu <notifications@github.com> wrote:

> Hi,
> I tried to run coupled FEM/BEM example on my laptop but I get this error:
>
> RuntimeError Traceback (most recent call last)
> in ()
> ----> 1 blocked[0,0] = A.weak_form()-k**2*A2.weak_form()
>
> /home/ali/repos/bempp/build/python_package/bempp/fenics_interface/fenics_operator.pyc
> in weak_form(self)
> 15
> 16 backend = _dolfin.parameters['linear_algebra_backend']
> ---> 17 _dolfin.parameters['linear_algebra_backend'] = 'uBLAS'
> 18 sparse_mat = _dolfin.assemble(self._fenics_weak_form).sparray()
> 19 _dolfin.parameters['linear_algebra_backend'] = backend
>
> /usr/lib/python2.7/dist-packages/dolfin/cpp/common.pyc in *setitem*(self,
> key, value)
> 2351 par._assign_bool(value)
> 2352 else:
> -> 2353 par._assign(value)
> 2354
> 2355 def update(self, other):
>
> RuntimeError:
>
> ***
> -------------------------------------------------------------------------
> *** DOLFIN encountered an error. If you are not able to resolve this issue
> *** using the information listed below, you can ask for help at
> ------------------------------
>
> *** fenics@fenicsproject.org
> ------------------------------
>
> *** Remember to include the error message listed below and, if possible,
> *** include a *minimal* running example to reproduce the error.
> ------------------------------
>
> ***
> -------------------------------------------------------------------------
> *** Error: Unable to assign parameter value.
> *** Reason: Illegal value for parameter "linear_algebra_backend". Allowed
> values are: [Eigen, PETSc, STL].
> *** Where: This error was encountered inside Parameter.cpp.
> *** Process: 0
> ------------------------------
>
> *** DOLFIN version: 1.6.0
> *** Git changeset: unknown
> ***
> -------------------------------------------------------------------------
>
> which seems to be related to this line:
> blocked[0, 0] = A.weak_form() - k**2*A2.weak_form()
> Could you please help me fix this?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/252>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by alineu** [comment]
Thanks a lot for quick reply. My BEM++ version is 2.9.9.
I also have another issue. I was able to run Laplace interior Dirichlet problem but when I try to run Acoustic wave scattering problem (Solving Boundary Integral Problems with BEM++ - section 4.2), I get this error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             __builtin__.execfile(filename, *where)

/home/ali/emacsusage/pyproject/AlinewBlocked.py in <module>()
      1 # PART 1: Importing Modules
      2 
----> 3 from bempp.lib import *
      4 import numpy as np
      5 

ImportError: No module named lib
I searched through other issues similar to mine (https://github.com/bempp/bempp/issues/204) but I couldn't fix it.
these are the folders in my bempp folder:
build/
cmake/
CMakeLists.txt
COPYING
create_debian_package.sh.in
doc/
examples/
lib/
LICENSE
MANIFEST.binary.in
MANIFEST.source.in
meshes/
python/
README
setup.py
tests/

and this is what I see in my lib/ folder:

assembly/       common/              Doxyfile.in       fiber/  hmat/  space/
CMakeLists.txt  config_bempp.in.hpp  doxygen_main.hpp  grid/   io/

I've realized there's another bempp folder inbempp/python having these:

assembly/       config.in.py       file_interfaces/  __init__.py  shapes/
CMakeLists.txt  external/          grid/             linalg/      space/
common/         fenics_interface/  hmat/             operators/   utils/

I appreciate if you help me out. 
Best wishes,
Ali

**Comment by tbetcke** [comment]
Dear Ali,

it seems that you are trying to run code for BEM++ 2.0 with the current version. We have redesigned and improved the interface quite a bit. You find some up to date tutorials on our homepage. You can also download the current version from there.

Best wishes

Timo

**Comment by tbetcke** [comment]
Dear Ali,

I have now uploaded a FEM/BEM example using the updated syntax. You can look at it in the tutorial section of the webpage.
Best wishes

Timo

**Comment by alineu** [comment]
Dear Timo,

I installed new BEMPP version and it works perfectly. I have this problem with my code though:
I'm trying to solve this BEM blocked equation:

<img src="http://www.sciweavers.org/tex2img.php?eq=%5Cbegin%7Bflushleft%7D%0A%5Cbegin%7Bbmatrix%7D0.5%20-%20K%5E%7Bmh%7D%20%26%20%5Calpha%20V%5E%7Bmh%7D%20-%20%5Cbeta%20%28V%5E%7Bmh%7D%20-%20V%29%20%26%20%5Cgamma%20%28K%5E%7Bmh%7D%20-%20K%29%20%5C%5C0.5%20%2B%20K%20%26%20-V%20%26%200%20%5C%5C0%20%26%20%5Calpha%20V%20%26%200.5%20-K%20%5Cend%7Bbmatrix%7D%20%20%5Cbegin%7Bbmatrix%7D%5Cphi%20%5C%5C%20%5Cfrac%7B%5Cpartial%20%5Cphi%7D%7B%5Cpartial%20n%7D%20%5C%5C%20%5Cpsi%20%20%5Cend%7Bbmatrix%7D%20%3D%20%5Cbegin%7Bbmatrix%7D%20%5Cxi%20%5C%5C%200%20%5C%5C%200%5Cend%7Bbmatrix%7D%20%0A%5C%5C%0A%7B%5Crm%20%7Bwhere%7D%7D%0A%5C%5C%0A%5Cxi%20%3D%20-%20%5Cbig%280.5%20-%20K%5E%7Bmh%7D%20-%20%5Cbeta%20%28K%5E%7Bmh%7D%20-%20K%29%20%5Cbig%29%20%20%5Cbegin%7Bbmatrix%7D%20%5Ceta%20%5Cend%7Bbmatrix%7D%20-%20%5Cbig%28%5Calpha%20V%5E%7Bmh%7D%20-%20%5Cbeta%20%28V%5E%7Bmh%7D%20-%20V%29%20%5Cbig%29%20%5Cbegin%7Bbmatrix%7D%20%5Cfrac%7B%5Cpartial%7B%5Ceta%7D%7D%7B%5Cpartial%20n%7D%20%5Cend%7Bbmatrix%7D%0A%5C%5C%0A%5Calpha%20%2C%20%5Cbeta%20%5Cquad%20%5Crm%7B%20and%7D%20%5Cquad%20%5Cgamma%20%5Cquad%20%5Crm%7Bare%7D%20%5Cquad%5Crm%7Bconstants%7D%0A%5Ceta%20%5Crm%7Bis%20%5Cquad%20a%20%5Cquad%20known%20%5Cquad%20function%7D%0A%5Cend%7Bflushleft%7D&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt="\begin{flushleft}\begin{bmatrix}0.5 - K^{mh} & \alpha V^{mh} - \beta (V^{mh} - V) & \gamma (K^{mh} - K) \\0.5 + K & -V & 0 \\0 & \alpha V & 0.5 -K \end{bmatrix}  \begin{bmatrix}\phi \\ \frac{\partial \phi}{\partial n} \\ \psi  \end{bmatrix} = \begin{bmatrix} \xi \\ 0 \\ 0\end{bmatrix} \\{\rm {where}}\\\xi = - \big(0.5 - K^{mh} - \beta (K^{mh} - K) \big)  \begin{bmatrix} \eta \end{bmatrix} - \big(\alpha V^{mh} - \beta (V^{mh} - V) \big) \begin{bmatrix} \frac{\partial{\eta}}{\partial n} \end{bmatrix}\\\alpha , \beta \quad \rm{ and} \quad \gamma \quad \rm{are} \quad\rm{constants}\eta \rm{is \quad a \quad known \quad function}\end{flushleft}" width="528" height="124" />

I use the following script to solve the problem:

import bempp.api
import numpy as np

k = 6.
d = np.array([1., 1., 1])
d /= np.linalg.norm(d)
eps_inf = 1
eps_bulk= 80
eps_phi = 3

grid = bempp.api.shapes.sphere(h=0.4)

bempp_space = bempp.api.function_space(grid,"DP",0)

print("BEM DOFs: {0}".format(bempp_space.global_dof_count))

#Creating the operators.

id_op = bempp.api.operators.boundary.sparse.identity(bempp_space, bempp_space, bempp_space)
dlp = bempp.api.operators.boundary.laplace.double_layer(bempp_space, bempp_space, bempp_space)
slp = bempp.api.operators.boundary.laplace.single_layer(bempp_space, bempp_space, bempp_space)
ydlp = bempp.api.operators.boundary.modified_helmholtz.double_layer(bempp_space, bempp_space, bempp_space, k)
yslp = bempp.api.operators.boundary.modified_helmholtz.single_layer(bempp_space, bempp_space, bempp_space, k)

#Make the vector on the right hand side of the formulation.
def dirichlet_data(x, n, domain_index, result):
    result[0] = 1./(4 * np.pi * (x[0]**2 + x[1]**2 + x[2]**2)**(0.5))
    
    
def neumann_data(x, n, domain_index, result):
    result = -np.dot(x,n)/(4 * np.pi * (x[0]**2 + x[1]**2 + x[2]**2)**(1.5))

    
dirichlet_fun = bempp.api.GridFunction(bempp_space, fun=dirichlet_data)
neumann_fun = bempp.api.GridFunction(bempp_space, fun=neumann_data)


# The rhs 
rhs_00 = -(.5 * id_op - ydlp -(eps_inf/eps_bulk) * (ydlp - dlp)) * dirichlet_fun -((eps_phi/eps_inf) * yslp - (eps_phi/eps_bulk) * (yslp - slp)) * neumann_fun
rhs_0 = rhs_00.projections(bempp_space)
rhs_1 = np.zeros(1392,dtype="complex128")


# The combined rhs
rhs = np.concatenate([rhs_0,rhs_1])
blocked = bempp.api.BlockedDiscreteOperator(3, 3)


blocked[0, 0] = (.5 * id_op - ydlp).weak_form()
blocked[0, 1] = (eps_phi/eps_inf) * yslp.weak_form() - (eps_phi/eps_bulk) * (ydlp-dlp).weak_form()
blocked[0, 2] = (eps_inf/eps_bulk) * (ydlp - dlp).weak_form()
blocked[1, 0] = (.5 * id_op + dlp).weak_form()
blocked[1, 1] = - slp.weak_form()
blocked[1, 2] = np.zeros((696,696),dtype="complex128")
blocked[2, 0] = np.zeros((696,696),dtype="complex128")
blocked[2, 1] = (eps_phi/eps_inf) * slp.weak_form()
blocked[2, 2] = (.5 * id_op - dlp).weak_form()


from scipy.sparse.linalg import LinearOperator

P1 = bempp.api.InverseSparseDiscreteBoundaryOperator(
    bempp.api.operators.boundary.sparse.identity(bempp_space, bempp_space, bempp_space).weak_form())

P2 = bempp.api.InverseSparseDiscreteBoundaryOperator(
    bempp.api.operators.boundary.sparse.identity(bempp_space, bempp_space, bempp_space).weak_form())

P3 = bempp.api.InverseSparseDiscreteBoundaryOperator(
    bempp.api.operators.boundary.sparse.identity(bempp_space, bempp_space, bempp_space).weak_form())

# Create a block diagonal preconditioner object using the Scipy LinearOperator class
def apply_prec(x):
    """Apply the block diagonal preconditioner"""
    m1 = P1.shape[0]
    m2 = P2.shape[0]
    m3 = P3.shape[0]
    
    n1 = P1.shape[1]
    n2 = P2.shape[1]
    n3 = P3.shape[1]
    
    res1 = P1.dot(x[:n1])
    res2 = P2.dot(x[n1:2*n1])
    res3 = P3.dot(x[2*n1:])
    return np.concatenate([res1, res2, res3])
p_shape = (P1.shape[0]+P2.shape[0]+P3.shape[0], P1.shape[1]+P2.shape[1]+P3.shape[1])
P = LinearOperator(p_shape, apply_prec, dtype=np.dtype('complex128'))


it_count = 0
def count_iterations(x):
    global it_count
    it_count += 1

from scipy.sparse.linalg import gmres
soln, info = gmres(blocked,rhs,M=P, callback=count_iterations)

soln_bem = soln[:1392]
soln_fem = soln[1392:]

print("Number of iterations: {0}".format(it_count))

but I get this error:

TypeError                                 Traceback (most recent call last)
<ipython-input-5-d1892b2c5711> in <module>()
     99 
    100 from scipy.sparse.linalg import gmres
--> 101 soln, info = gmres(blocked,rhs,M=P, callback=count_iterations)
    102 
    103 soln_bem = soln[:1392]

/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/iterative.pyc in gmres(A, b, x0, tol, restart, maxiter, xtype, M, callback, restrt)

/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/iterative.pyc in non_reentrant(func, *a, **kw)
     83     try:
     84         d['__entered'] = True
---> 85         return func(*a, **kw)
     86     finally:
     87         d['__entered'] = False

/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/iterative.pyc in gmres(A, b, x0, tol, restart, maxiter, xtype, M, callback, restrt)
    472         elif (ijob == 3):
    473             work[slice2] *= sclr2
--> 474             work[slice2] += sclr1*matvec(work[slice1])
    475             if resid_ready and callback is not None:
    476                 callback(resid)

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in matvec(self, x)
    122                 raise ValueError('dimension mismatch')
    123 
--> 124             y = self._matvec(x)
    125 
    126             if isinstance(x, np.matrix):

/usr/lib/python2.7/dist-packages/bempp/api/assembly/blocked_operator.py in _matvec(self, x)
    169         if x.ndim == 1:
    170             x_new = _np.expand_dims(x, 1)
--> 171             return self.matvec(x_new).ravel()
    172 
    173         if not self._fill_complete():

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in matvec(self, x)
    122                 raise ValueError('dimension mismatch')
    123 
--> 124             y = self._matvec(x)
    125 
    126             if isinstance(x, np.matrix):

/usr/lib/python2.7/dist-packages/bempp/api/assembly/blocked_operator.py in _matvec(self, x)
    188                                          1j * self._operators[i, j] * _np.imag(local_x))
    189                     else:
--> 190                         local_res[:] += self._operators[i, j].dot(local_x)
    191                 col_dim += self._cols[j]
    192             row_dim += self._rows[i]

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in dot(self, x)
    252 
    253                 if x.ndim == 1 or x.ndim == 2 and x.shape[1] == 1:
--> 254                     return self.matvec(x)
    255                 elif x.ndim == 2:
    256                     return self.matmat(x)

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in matvec(self, x)
    122                 raise ValueError('dimension mismatch')
    123 
--> 124             y = self._matvec(x)
    125 
    126             if isinstance(x, np.matrix):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in _matvec(self, x)
    379 
    380         def _matvec(self, x):
--> 381             return self.args[0].matvec(x) + self.args[1].matvec(x)
    382 
    383         def _rmatvec(self, x):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in matvec(self, x)
    122                 raise ValueError('dimension mismatch')
    123 
--> 124             y = self._matvec(x)
    125 
    126             if isinstance(x, np.matrix):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in _matvec(self, x)
    429 
    430         def _matvec(self, x):
--> 431             return self.args[1] * self.args[0].matvec(x)
    432 
    433         def _rmatvec(self, x):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in matvec(self, x)
    122                 raise ValueError('dimension mismatch')
    123 
--> 124             y = self._matvec(x)
    125 
    126             if isinstance(x, np.matrix):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in _matvec(self, x)
    429 
    430         def _matvec(self, x):
--> 431             return self.args[1] * self.args[0].matvec(x)
    432 
    433         def _rmatvec(self, x):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in matvec(self, x)
    122                 raise ValueError('dimension mismatch')
    123 
--> 124             y = self._matvec(x)
    125 
    126             if isinstance(x, np.matrix):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in _matvec(self, x)
    379 
    380         def _matvec(self, x):
--> 381             return self.args[0].matvec(x) + self.args[1].matvec(x)
    382 
    383         def _rmatvec(self, x):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in matvec(self, x)
    122                 raise ValueError('dimension mismatch')
    123 
--> 124             y = self._matvec(x)
    125 
    126             if isinstance(x, np.matrix):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in _matvec(self, x)
    429 
    430         def _matvec(self, x):
--> 431             return self.args[1] * self.args[0].matvec(x)
    432 
    433         def _rmatvec(self, x):

/usr/lib/python2.7/dist-packages/bempp/api/utils/linear_operator.py in matvec(self, x)
    122                 raise ValueError('dimension mismatch')
    123 
--> 124             y = self._matvec(x)
    125 
    126             if isinstance(x, np.matrix):

/usr/lib/python2.7/dist-packages/bempp/api/assembly/discrete_boundary_operator.py in _matvec(self, vec)
     22         """Implements matrix-vector product."""
     23 
---> 24         return self._impl.matvec(vec)
     25 
     26     def _matmat(self, vec): # pylint: disable=method-hidden

bempp/core/assembly/discrete_boundary_operator.pyx in bempp.core.assembly.discrete_boundary_operator.RealDiscreteBoundaryOperator.matvec (/bempp_build/bempp/build/cython/bempp/core/assembly/cython_discrete_boundary_operator.cc:2499)()

TypeError: unsupported operand type(s) for *: 'bempp.core.assembly.discrete_boundary_operator.RealDiscreteBoundaryOperator' and 'float'

I tried to debug it but I wasn't successful. I was wondering if you can help me figure out what might be the problem. Thank you so much.

Best wishes,
Ali

**Comment by tbetcke** [comment]
Dear Alineu,

when I am running your code I get a lot of errors about incompatible dimensions. You should start checking this. Also, right now you cannot directly put zero np arrays into a blocked operator. You either need to turn them into a linear operator via the scipy aslinearoperator function or you can just leaf them out. If an operator is not assigned to a block it is treated as zero.

However, please use for such questions which are not BEM++ bugs the forum and not our bug tracking system.
Best wishes

Timo

**Comment by alineu** [comment]
Dear Timo,

Thanks for your answer and sorry about using this page. I will use the forum from now on for my further problems.

Best wishes,
Ali
