### ISSUE TITLE
VirtualBox cannot import .ova image

### ISSUE THREAD

**Issue by deweylake** [bempp/bempp#254]
It appears that the image is damaged.
Here is the error from VirtualBox:

Failed to import appliance C:\\Downloads\BEMPP\Ubuntu_BEMPP_3.0.0.ova.

Could not create the imported medium 'C:\VBox\Ubuntu_BEMPP_3.0.0\Ubuntu_BEMPP_3.0.0-disk1.vmdk'.

VMDK: Compressed image is corrupted 'C:\Users\########\Ubuntu_BEMPP_3.0.0-disk1.vmdk' (VERR_ZIP_CORRUPTED).

Result Code: VBOX_E_FILE_ERROR (0x80BB0004)
Component: ApplianceWrap
Interface: IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

**Comment by tbetcke** [comment]
Thanks. I just checked and their was a file transfer issue to the web server. Will fix today.
Timo

**Comment by tbetcke** [comment]
I have now uploaded the VirtualBox image again and tested it by downloading and importing. Everything worked fine. I am closing the issue. Please reopen if further problems appear.
