### ISSUE TITLE
Compiling BEM++ on Mac issue: "make -j4" step on installation instructions

### ISSUE THREAD

**Issue by AdolfoVillalobos** [bempp/bempp#259]
Hi everyone.

Im currently trying to install bempp on my macbook pro, by home-brew installation and im stuck on the "make -j4" step. Im getting this on the screen (terminal)

![screen shot 2016-01-10 at 11 32 34 pm](https://cloud.githubusercontent.com/assets/16639270/12225898/a475f3f6-b7f2-11e5-88f1-b8bdd7f4d1e8.png)
![screen shot 2016-01-10 at 11 32 54 pm](https://cloud.githubusercontent.com/assets/16639270/12225900/af992046-b7f2-11e5-8c34-97893534bd82.png)
![screen shot 2016-01-10 at 11 33 07 pm](https://cloud.githubusercontent.com/assets/16639270/12225903/b3be1528-b7f2-11e5-9e93-076b6484ba1f.png)
![screen shot 2016-01-10 at 11 33 23 pm](https://cloud.githubusercontent.com/assets/16639270/12225906/b6911e30-b7f2-11e5-84b9-e283f706d2aa.png)

I`ve followed all the steps, but i really don't know what to do.

If you can help me, it will be great

Best regards

**Comment by tbetcke** [comment]
Hi,

there is an issue compiling unit tests with the most recent Boost version. You can switch off the compilation of the unit tests with the cmake parameter -DWITH_TESTS=OFF. Then it should work. If you install with Homebrew, that is use "brew install bempp" this parameter is automatically passed.

Timo

**Comment by AdolfoVillalobos** [comment]
I did what you say (on bemmp folder, where the build folder is contained), and i got these message now.

I installed it with homebrew, should i re-install it?.

![screen shot 2016-01-12 at 12 52 36 pm](https://cloud.githubusercontent.com/assets/16639270/12268472/bc5f513a-b92b-11e5-9e6c-6c8cca6c5b50.png)

![screen shot 2016-01-12 at 12 52 56 pm](https://cloud.githubusercontent.com/assets/16639270/12268484/c24e34b2-b92b-11e5-9079-e2087a1979b4.png)

![screen shot 2016-01-12 at 12 53 08 pm](https://cloud.githubusercontent.com/assets/16639270/12268489/c5a55668-b92b-11e5-8629-f434ab543ec4.png)

**Comment by tbetcke** [comment]
Hi Adolfo,

I don't quite understand what you are saying. When you install with
Homebrew you do not download bempp and create a build directory.
You just somewhere in your filesystem say "brew install bempp". Everything
then gets downloaded into a temporary directory, compiled and installed
from there. Could you clarify whether you have downloaded it and manually
used cmake and make or whether you used Homebrew?

Timo

On 12 January 2016 at 15:55, AdolfoVillalobos <notifications@github.com>
wrote:

> I did what you say (on bemmp folder, where the build folder is contained),
> and i got these message now.
>
> I installed it with homebrew, should i re-install it?.
>
> [image: screen shot 2016-01-12 at 12 52 36 pm]
> <https://cloud.githubusercontent.com/assets/16639270/12268472/bc5f513a-b92b-11e5-9e6c-6c8cca6c5b50.png>
>
> [image: screen shot 2016-01-12 at 12 52 56 pm]
> <https://cloud.githubusercontent.com/assets/16639270/12268484/c24e34b2-b92b-11e5-9079-e2087a1979b4.png>
>
> [image: screen shot 2016-01-12 at 12 53 08 pm]
> <https://cloud.githubusercontent.com/assets/16639270/12268489/c5a55668-b92b-11e5-8629-f434ab543ec4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/259#issuecomment-170955681>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by AdolfoVillalobos** [comment]
Maybe i understand the process wrong. If you go to the Installation instructions, y followed the "Installation on MacOS using Homebrew" steps and it was okey. Maybe wh at im doing wrong is continuing with the steps of "Building BEM++ from scratch".  I think thats it (im not and english native so i got a little confused)

**Comment by tbetcke** [comment]
Dear Adolfo,

that's it. The "Building BEM++ from scratch" section is not needed for you.
This is a different method for people who want to have access to the C++
source codes. You only need the Homebrew section. If everything went fine
there you can simply try it by starting python and then running

import bempp.api

If no error message is coming then BEM++ is installed using your Homebrew
Python.

Best wishes

Timo

On 12 January 2016 at 17:28, AdolfoVillalobos <notifications@github.com>
wrote:

> Maybe i understand the process wrong. If you go to the Installation
> instructions, y followed the "Installation on MacOS using Homebrew" steps
> and it was okey. Maybe wh at im doing wrong is continuing with the steps of
> "Building BEM++ from scratch". I think thats it (im not and english native
> so i got a little confused)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/259#issuecomment-170983329>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by AdolfoVillalobos** [comment]
Thank you, i was suffering for nothing haha. Indeed there is no error message. Again ,thank you so much.
Best regards.

Adolfo

**Comment by tbetcke** [comment]
No problem. Let us know if you need any further help.

Timo

On 12 January 2016 at 17:45, AdolfoVillalobos <notifications@github.com>
wrote:

> Thank you, i was suffering for nothing haha. Indeed there is no error
> message. Again ,thank you so much.
> Best regards.
>
> Adolfo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bempp/bempp/issues/259#issuecomment-170987958>.
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519
