### ISSUE TITLE
Problem with Matplotlib

### ISSUE THREAD

**Issue by AdolfoVillalobos** [bempp/bempp#260]
Hey everyone!.

I'm running the first tutorial code on my macbook pro (the laplace example), and i'm having trouble with the plot section.

i get this error:

![screen shot 2016-01-21 at 11 06 53 am](https://cloud.githubusercontent.com/assets/16639270/12482581/2fb0766e-c02f-11e5-8bf3-9026c8fab116.png)
![screen shot 2016-01-21 at 11 07 08 am](https://cloud.githubusercontent.com/assets/16639270/12482586/3465959a-c02f-11e5-8023-e82849071835.png)
![screen shot 2016-01-21 at 11 07 20 am](https://cloud.githubusercontent.com/assets/16639270/12482587/3854f33a-c02f-11e5-9380-226ef02d6889.png)

The code is this:

![screen shot 2016-01-21 at 11 08 12 am](https://cloud.githubusercontent.com/assets/16639270/12482603/51329060-c02f-11e5-94dd-595bce700a75.png)

![screen shot 2016-01-21 at 11 08 25 am](https://cloud.githubusercontent.com/assets/16639270/12482606/54b3fd50-c02f-11e5-97ab-e1cc88dc0e25.png)

Thank you for the previous help

**Comment by mscroggs** [comment]
Looks like this might be a known issue with matplotlib: https://github.com/matplotlib/matplotlib/issues/5420

Can you try running `export LANG=en_US.UTF-8` in terminal then your code again.

**Comment by AdolfoVillalobos** [comment]
Hi! Thank you for the quick answer.  I'm doing what you say, but im still having the same problem.

![screen shot 2016-01-21 at 11 19 00 am](https://cloud.githubusercontent.com/assets/16639270/12482876/cde02284-c030-11e5-84b3-37348c1ecd66.png)

Maybe i should reinstall everything?

**Comment by mscroggs** [comment]
Can you run
```import locale
locale.getdefaultlocale()```
in Python to see if it causes an error

**Comment by AdolfoVillalobos** [comment]
Yes, it causes an error:

![screen shot 2016-01-21 at 11 30 19 am](https://cloud.githubusercontent.com/assets/16639270/12483209/6b784458-c032-11e5-9900-8cf7e70a0b30.png)

**Comment by mscroggs** [comment]
Try running `export LC_ALL=en_US.UTF-8` then `export LANG=en_US.UTF-8` in terminal then re-running.

**Comment by AdolfoVillalobos** [comment]
Now i have no errors:

![screen shot 2016-01-21 at 11 39 33 am](https://cloud.githubusercontent.com/assets/16639270/12483412/ab5f0682-c033-11e5-9fd6-81e9c4d052c2.png)

The problem now is that the plot isn`t opening (python will open and close in less than a second). Is there any fix to this??

**Comment by thisch** [comment]
@AdolfoVillalobos Try to put ``plt.show()`` at the end of your file

**Comment by AdolfoVillalobos** [comment]
Thank you! that was it! 

This was a big big help, thank you all, it works now!.

Thank you for the patience, best regards!

**Comment by mscroggs** [comment]
If you add those two commands to your `.bashrc` file, then the fix will be permanent (I'm on Ubuntu not Mac so it might be a different file for you).

`plt.savefig(filename)` is also useful: it will save your image then you can open it.
