### ISSUE TITLE
How to get domain_indices from a grid

### ISSUE THREAD

**Issue by AdolfoVillalobos** [bempp/bempp#265]
Hey guys, maybe this is a silly question but i have to ask anyways.

I want to know the domain_indices from a grid defined by a .msh file. This comes in the GridView class, but im not sure about how to call it. I tried a few times defining first the grid and then a grid_view objet, and then calling the function but it is not working. Can you give a clue about how to call it?

**Comment by tbetcke** [comment]
Dear Adolfo,

that's very simple. If you have a grid you get the elements by
grid.leaf_view.elements and the associated domain indices by grid.leaf_view.domain_indices.
The vertices are grid.leaf_view.vertices

Best wishes

Timo
