### ISSUE TITLE
Alternative Boost install

### ISSUE THREAD

**Issue by skrot-nisse** [bempp/bempp#267]
Building bempp boost is downloaded and installed. I would like to use my own installation of boost, at a location that cmake automatically can't find, for example /usr/local/boost/boost_1_60_0.

Is there a way to add flag to cmake and bulid bempp this way?

**Comment by mdavezac** [comment]
For all and any library, the simplest is to run cmake with:

```
cmake -DCMAKE_PREFIX_PATH=/path/special/prefix [other options]
```

This will add `/path/special/prefix/lib`, `/path/special/prefix/include` and friends to the relevant search paths.

There are more specific options if you want to add a prefix that will only be used by Boost. Please google `FindBoost.cmake` for details.

**Comment by skrot-nisse** [comment]
I tried this and the default cmake command:

cmake -DCMAKE_INSTALL_PREFIX=my_bempp-install-path -DBOOST_ROOT=my_boost_path ..

and

cmake -DCMAKE_INSTALL_PREFIX=my_bempp-install-path ..

But it's failing to build with the following error (removed the build dir after every trial):

[ 22%] Built target TBB
-- Boost download command succeeded.  See also /usr/local/bempp/bempp-master/build/external/src/Boost-stamp/Boost-download-*.log
[ 22%] No patch step for 'Boost'
[ 22%] No update step for 'Boost'
[ 22%] Performing configure step for 'Boost'
-- Boost configure command succeeded.  See also /usr/local/bempp/bempp-master/build/external/src/Boost-stamp/Boost-configure-*.log
[ 23%] Performing build step for 'Boost'
CMake Error at /usr/local/bempp/bempp-master/build/external/src/Boost-stamp/Boost-build-RelWithDebInfo.cmake:16 (message):
  Command failed: 1

   '/usr/local/bempp/bempp-master/build/external/src/boost_configure.sh'

  See also

    /usr/local/bempp/bempp-master/build/external/src/Boost-stamp/Boost-build-*.log


CMakeFiles/Boost.dir/build.make:112: recipe for target 'external/src/Boost-stamp/Boost-build' failed
make[2]: *** [external/src/Boost-stamp/Boost-build] Error 1
CMakeFiles/Makefile2:241: recipe for target 'CMakeFiles/Boost.dir/all' failed
make[1]: *** [CMakeFiles/Boost.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

What can I do in order to pass this?

/Erik

**Comment by skrot-nisse** [comment]
Solution

In: xxx/bempp/build/external/src/Boost-stamp/Boost-build-out.log 

I had the line:

libs/iostreams/src/bzip2.cpp:20:56: fatal error: bzlib.h: No such file or directory
compilation terminated.

Installed libbz2-dev,

sudo apt-get install libbz2-dev

And building bempp went well.
