### ISSUE TITLE
Supplementary Material 

### ISSUE THREAD

**Issue by chrisargyros22** [bempp/bempp#273]
Dear BEM++ team,
I was reading the paper you wrote "Solving Boundary Integral Problems with BEM++" and I have seen that you said that some examples may be found in the Supplementary Material. Where exactly is this? Where can I find these examples? (I mean the full code of course)
Thank you in advance.
Best regards 
Chris

**Comment by mscroggs** [comment]
The paper is based on an old version of BEM++. Example code for the newest version can be found at http://www.bempp.org/tutorials.html

**Comment by chrisargyros22** [comment]
Thank a lot! I'm aware that it was about an old version of BEM++. I was just wondering if it's possible to have these examples as there may be pretty useful for my work.

Chris

**Comment by mscroggs** [comment]
I started working on a website update today, and found them! They are linked to from http://www.bempp.org/publications.html

**Comment by chrisargyros22** [comment]
Oh that's great! Thank you very much!
