### ISSUE TITLE
VTK export

### ISSUE THREAD

**Issue by arieder** [bempp/bempp#277]
Hi,
In previous versions of Bem++ there was the option to export GridFunctions to the Vtk format. I've been using this functionality to assemble animations for time-dependent problems in Paraview. 
When switching to Bem++3, I was unable to find out how to do this (even though some code related to Vtk seems to still be around). Is there any way to export to Vtk in the latest Bem++ or is there any other way to conveniently assemble an animation using a GridFunction for each frame?

best regards,
Alexander

**Comment by tbetcke** [comment]
Hi Alexander,

we currently have no VTK support in BEM++ 3. The reason is that BEM++ 3 is
Python 3 compatible. But until very recently there was no VTK version for
Python 3. So we had to rewrite the export and visualization. We are now
using the Gmsh format for expert. From Gmsh you can easily export to VTK as
well. Details of the new export routines are described in
http://www.bempp.org/gmsh_interface.html. Once VTK for Python 3 becomes
widely available in distributions we may offer VTK export again.

Best wishes

Timo

On 13 July 2016 at 16:03, arieder <notifications@github.com> wrote:

> Hi,
> In previous versions of Bem++ there was the option to export GridFunctions
> to the Vtk format. I've been using this functionality to assemble
> animations for time-dependent problems in Paraview.
> When switching to Bem++3, I was unable to find out how to do this (even
> though some code related to Vtk seems to still be around). Is there any way
> to export to Vtk in the latest Bem++ or is there any other way to
> conveniently assemble an animation using a GridFunction for each frame?
>
> best regards,
> Alexander
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bempp/bempp/issues/277>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAHNKI5r2UYNsPsi7kMmFob2mlyuVmcvks5qVP47gaJpZM4JLhB9>
> .
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519

**Comment by arieder** [comment]
Hi Timo,
thanks, I think I got it working using Gmsh. Allthough I would be welcome  seeing VTK working again in the future.

thanks,
Alex

**Comment by chrisargyros22** [comment]
Dear Alex,
Could you please explain the process on how you got it working using Gmsh
as I'm interested in the exact same thing.
Thank you in advance.
Chris

2016-07-14 17:19 GMT+03:00 arieder <notifications@github.com>:

**Comment by arieder** [comment]
Hi Chris,
I guess I should clarify, that I didn't manage to export to Paraview(as far as I can see, the GMsh vtk export only exports geometry not gridfunctions), but instead use Gmsh directly to create the animations I wanted. 

Alex

**Comment by chrisargyros22** [comment]
Oh, OK then, Nevertheless, thank you very much! But if you don't mind can
you explain how you actually create those animations?

2016-07-14 18:10 GMT+03:00 arieder <notifications@github.com>:

**Comment by arieder** [comment]
Sure, I basically exported all my frames as separate gmsh files(this script does so for a simple travelling wave)
```
import bempp.api


from numpy import *;



grid = bempp.api.shapes.cube(h=0.1)

const_space = bempp.api.function_space(grid, "DP", 0)
lin_space = bempp.api.function_space(grid, "P", 1)

def basewave_p(s):
    A=2.5;
    sigma=0.5;
    omega=4*pi;

    sc=( ( s )-A )/sigma;

    return ( omega*sin( omega*s )*exp( -sc*sc )+  cos( omega*s )*sc*( 2.0/sigma )*exp( -sc*sc ) );



n=256;
Tend=8;
for i in range(0,n+1):
  t=i*(Tend/(n));
  def funuinc(x,n,domain_index,result):
    ts=t;

    d=asarray([1.0,0.1,0.0]);
    d/=linalg.norm(d,2);

    result[0]=basewave_p( ts - x.dot(d))

  psi=bempp.api.assembly.GridFunction( lin_space, fun=funuinc );
  #psi.plot();                                                                                                                                                                               
  filename="frame"+str(i).zfill(4)+".msh";

  bempp.api.export(grid_function=psi, file_name=filename)

```
Then in gmsh i can combine these files into one, and export the animation (this can be done by hand or using this script I cobbled together from the gmsh examples):

```
//number of frames in the animation
nanims=256;

//load all the views
For i In {1:nanims}
  Merge Sprintf("psi_frame%04g.msh",i);
  View[PostProcessing.NbViews-1].Visible = 0;
EndFor

// set the dimension of the animation
General.GraphicsWidth = 1024;
General.GraphicsHeight = 1024 ;

// Set max jpeg quality

Print.JpegQuality = 100;


// Hide all views
View[0].Visible = 1;

For i In {1: PostProcessing.NbViews}
  View[i-1].Visible = 0;
EndFor

Combine TimeStepsFromAllViews;


index = 0;

View[0].Visible = 1;

For i In {1:View[0].NbTimeStep}
  index++;
  Draw;
// generate a jpeg image
  Print Sprintf("anim-%03g.png", index);
  View[0].TimeStep++;
EndFor


//System "mencoder 'mf://*.png' -mf fps=16 -o anim.mpg -ovc lavc -lavcopts vcodec=mpeg1video:vhq";
//System "mencoder 'mf://*.png' -mf fps=16 -o anim.mpg -ovc lavc -lavcopts vcodec=mpeg4:vhq";
System "mencoder 'mf://*.png' -mf w=1024:h=1024:fps=25:type=png -ovc x264 -x264encopts preset=slow:tune=film:crf=20 -of rawvideo -o anim.avi";


// Clean-up all temp files

//System "rm -f anim-*.gif" ;
System "rm -f anim-*.png" ;
//System "rm -f anim.par" ;
```
If you open this script in gmsh it should give you a movie called anim.avi
(this script assumes you have mencoder installed on your system)
