### ISSUE TITLE
Problem with Fenics_Operator

### ISSUE THREAD

**Issue by michaelFeischl** [bempp/bempp#288]
Dear BEM++ Team,

When I run the following code on the latest version of BEM++

```
from dolfin import *
import bempp
from bempp.api.fenics_interface import FenicsOperator

    
mesh = UnitCubeMesh(5,5,5)
   
NDvol = FunctionSpace(mesh,"N1curl",1)
      
H = dolfin.TrialFunction(NDvol)
xi = dolfin.TestFunction(NDvol)
      
A  = FenicsOperator((dolfin.inner(H,xi)*dolfin.dx))
B  = A.weak_form()
```

I get the following error message:

> Traceback (most recent call last):
>   File "minimal.py", line 14, in <module>
>     B  = A.weak_form()
>   File "/usr/lib/python2.7/dist-packages/bempp/api/fenics_interface/fenics_operator.py", line 22, in weak_form
>     A = as_backend_type(assemble(self._fenics_weak_form)).mat()
>   File "/usr/lib/python2.7/dist-packages/dolfin/cpp/la.py", line 1768, in mat
>     "dolfin must be configured with petsc4py enabled")
>   File "/usr/lib/python2.7/dist-packages/dolfin/cpp/common.py", line 2296, in dolfin_error
>     return _common.dolfin_error(*args)
> RuntimeError: 
> 
> *** -------------------------------------------------------------------------
> *** DOLFIN encountered an error. If you are not able to resolve this issue
> *** using the information listed below, you can ask for help at
> ***
> ***     fenics@fenicsproject.org
> ***
> *** Remember to include the error message listed below and, if possible,
> *** include a *minimal* running example to reproduce the error.
> ***
> *** -------------------------------------------------------------------------
> *** Error:   Unable to access PETScMatrix objects in python.
> *** Reason:  dolfin must be configured with petsc4py enabled.
> *** Where:   This error was encountered inside dolfin/swig/la/post.i.
> *** Process: 0
> *** 
> *** DOLFIN version: 1.3.0
> *** Git changeset:  unknown
> *** -------------------------------------------------------------------------

The code used to work on older versions of BEM++. What can I do here? Thanks for any help.

Best,
Michael

**Comment by michaelFeischl** [comment]
I found a workaround: Just set

`parameters['linear_algebra_backend']='uBLAS'`

That seems to do the trick. Is that a clean solution?

**Comment by mscroggs** [comment]
Hi Michael,

Setting the backend to uBLAS is a good way to get around the problem (and avoids rebuilding FEniCS and petsc2py).

In case others find this issue in future, you can also use

`parameters['linear_algebra_backend']='Eigen'`

to get around this error if you have eigen installed but not uBLAS.

**Comment by michaelFeischl** [comment]
Thanks
