### ISSUE TITLE
Cannot compile bempp from source

### ISSUE THREAD

**Issue by pafluxa** [bempp/bempp#300]
Greetings,

I am trying to compile BEM++ from source to use it inside the Cluster at Pontificia Universidad Catolica de Chile. I am following all the directions in the webpage, but I am getting this error

-- The CXX compiler identification is GNU 4.8.2
-- Check for working CXX compiler: /opt/compilers/gcc/gcc-4.8.2/bin/g++
-- Check for working CXX compiler: /opt/compilers/gcc/gcc-4.8.2/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Checking if CXX linker supports --verbose
-- Checking if CXX linker supports --verbose - yes
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
BEM++ Version 3.1.5
-- The C compiler identification is GNU 4.8.2
-- Check for working C compiler: /opt/compilers/gcc/gcc-4.8.2/bin/gcc
-- Check for working C compiler: /opt/compilers/gcc/gcc-4.8.2/bin/gcc -- works
-- Detecting C compiler ABI info
-- Checking if C linker supports --verbose
-- Checking if C linker supports --verbose - yes
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Will attempt to download and install Eigen3
-- Will attempt to download and install Boost
-- Will attempt to download and install TBB
-- Will attempt to download and install Dune
-- Found Patchelf
-- Found MPI_C: /opt/programs/anaconda2-4.1.1/lib/libmpi.so  
-- Found MPI_CXX: /opt/programs/anaconda2-4.1.1/lib/libmpicxx.so;/opt/programs/anaconda2-4.1.1/lib/libmpi.so  
-- Found Cython: /usr/lib64/python2.6/site-packages/Cython (found suitable version "0.25.2", minimum required is "0.21") 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'major'
CMake Error at cmake/CPackConfig.cmake:10 (if):
  if given arguments:

    "EQUAL" "3"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:113 (include)

-- Configuring incomplete, errors occurred!

Any ideas on how to fix this?

**Comment by tbetcke** [comment]
Dear Pedro,

what Linux environment and in particular what CMake version are you using?
Also, could you please send anything that is not a direct bug report to the Bempp Google Forum at 
https://groups.google.com/forum/#!forum/bempp ?

Best wishes

Timo
