### ISSUE TITLE
problem of installing BEM++

### ISSUE THREAD

**Issue by flightime** [bempp/bempp#301]
Hi All
I am installing BEM++ on fedora 23, but I encounter a problem 

`BEM++ Version 3.1.5
-- Found Eigen3
-- Found Boost
-- Will attempt to download and install TBB
-- Will attempt to download and install Dune
-- Found Patchelf
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindMPI.cmake:614 (find_package_handle_standard_args)
  cmake/BemppFindDependencies.cmake:86 (find_package)
  CMakeLists.txt:62 (include)

-- Configuring incomplete, errors occurred!
See also "/home/yxz/bempp/build/CMakeFiles/CMakeOutput.log".
`

can anyone help me, I really appreciate.

**Comment by tbetcke** [comment]
Hi,

From Bempp 3.1 onwards MPI libraries are required to be present on the system. However, why are you simply using the Docker images? It is the easiest and our main supported way to run Bempp.

Could you please ask further questions on our Google Groups forum? That's our main place for non-bug related discussions around Bempp.
Best wishes

Timo
