### ISSUE TITLE
Docker image error

### ISSUE THREAD

**Issue by xiamengqi2012** [bempp/bempp#302]
I got "docker: invalid reference format." error from running the following command: docker run -it –rm -v $(pwd):/home/bempp/work -p 8888:8888 bempp/notebook. May I know why?

**Comment by tbetcke** [comment]
You need to use a double dash in front of the rm. The HTML did not display this well. I fixed it now in the docs. Can I please ask you in the future to use the bempp Google forum at https://groups.google.com/forum/#!forum/bempp for questions?

Best wishes

Timo
