### ISSUE TITLE
Avoid re-setup of weak forms 

### ISSUE THREAD

**Issue by florian98765** [bempp/bempp#91]
Hello, 

I would like to multiply an integral operator with multiple input vectors like shown in this code snippet:

    def func(x)
        x_BEM = createGridFunction(context, pwiseLinears, pwiseLinears, coefficients=x)
        res = dlpOp*x_BEM 
        return res.coefficients()

    func(x1)
    func(x2)

If i do so, it seems that weak form of the operator as well as its (pseudo) inverse is setup twice:

    Assembling the weak form of operator 'Op1'...
    Collecting data for assembler construction...
    Data collection finished.
    Assembly of the weak form of operator 'Op1' took 0.000431175 s
    Calculating the (pseudo)inverse of operator 'Op1'...
    Calculation of the (pseudo)inverse of operator 'Op1' took 0.00013551 s

    Assembling the weak form of operator 'Op2'...
    Collecting data for assembler construction...
    Data collection finished.
    Assembly of the weak form of operator 'Op2' took 0.000433189 s
    Calculating the (pseudo)inverse of operator 'Op2'...
    Calculation of the (pseudo)inverse of operator 'Op2' took 0.000134808 s

Is there a way to avoid this? is the (pseudo) inverse needed for a simple matrix-vector-multiplication? 

Can the GridFunction object be reused anyhow? only resetting its coefficients, or is this not a big overhead?

thanks 
Florian

**Comment by florian98765** [comment]
Hello again, 

we are still coping with the problem of multiple input vectors. perhaps you could give some more advice about the implementation.

i tried "dlOp=createHelmholtz3dDoubleLayerBoundaryOperator(...).weakForm().asMatrix()", but then i do not get the mulitplication with my gridFunction working. I am also wondering how this would work in combination with an ACA operator? 

recent benchmarks show the for a single matrix vector multiplication (without setup of the operator) the creation and application of the Pseudoinverse has indeed a significant contribution to the execution time. So i would like to extract the DiscreteBoundaryOperator as Wojciech suggests. Could you provide a simple example how this can be achieved?

thanks again,
greetings
Florian

**Comment by tbetcke** [comment]
Hi Florian,

when you use the command "dlOp=createHelmholtz3dDoubleLayerBoundaryOperator(...).weakForm().asMatrix()"
you get back a standard Numpy array. This is not overloaded for multiplication with grid functions. So you then need to extract the coefficient vector from the grid function and use

     res = dlOp*coefficients.

The result is now a standard Numpy vector of projections onto the "dual_to_range" space of the operator. To recover the coefficients in the original space. You need to set up an identity operator in the form

id = createIdentityOperator(dlOp.range,dlOp.dualToRange(),dlOp.dualToRange).weakForm().asMatrix().

You can now solve the system of equations id*x = res. If id is square you use LU, if it is overdetermined you can try a Least-Squares solve (e.g. pseudoinverse). These steps are exactly what a GridFunction is doing. The only potential savings are if you can store the LU factorisation of the pseudo-inverse. However, in BEM++ 2 the command asMatrix() always returns a dense matrix. A GridFunction internally uses sparse matrix algebra, which is a lot faster even for medium size problems. In the development branch of BEM++ we have direct access to the sparse matrix structure enabled.

Best wishes

Timo

**Comment by wsmigaj** [comment]
Hi Florian,

to avoid the call to ``asMatrix()`` and hence the conversion of the sparse representation of the discrete weak form of the identity operator into a dense matrix, you need to create an ``AbstractBoundaryOperatorPseudoinverse`` object -- an abstract boundary operator representing the pseudoinverse of a boundary operator. Internally, it uses sparse LU to invert sparse matrices. In the C++ version of BEM++ such an operator can be constructed using the ``pseudoinverse()`` function, but in BEM++ 2.0 this function is not available from Python. However, I have added a wrapper of this function in a new branch of BEM++, ``features/python-pseudoinverse``. This makes it possible to write, for example
```
idOp = createIdentityOperator(context, dlpOp.range(), dlpOp.range(), dlpOp.dualToRange())
invIdOp = pseudoinverse(idOp)
discreteInvIdOp = invIdOp.weakForm()
discreteDlpOp = dlpOp.weakForm()
result = discreteInvIdOp * (discreteDlpOp * dirichletData.coefficients())
```
The array ``result`` generated by the above snippet is identical to what you would get from ``(dlpOp * dirichletData).coefficients()``, but the calculation of the pseudoinverse of the identity operator's matrix is done in advance in the ``discreteInvIdOp = invIdOp.weakForm()`` line, so it can be reused in further multiplications.

If you wish, you can make the Python wrapper for ``pseudoinverse`` available in your installation of BEM++ by going to the BEM++ source directory and running
```
git pull
git checkout features/python-pseudoinverse
cd build/bempp
make install
```
Best regards,
Wojciech

**Comment by florian98765** [comment]
Hi again,

Thanks Timo and Wojciech for your detailed reply and the created feature 
branch! We implemented the suggested changes and were able to achieve a 
speedup of a factor 7 for a single BEM matrix vector multiplication.

greetings
Florian
